DROP TABLE IF EXISTS `ruleParagraph`;

--
-- Table structure for table `ruleParagraph`
--

CREATE TABLE IF NOT EXISTS `ruleParagraph` (
  `ruleId` int(3) NOT NULL,
  `sectionId` varchar(10) NOT NULL,
  `paragraphId` int(3) NOT NULL,
  `paragraphText` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `paragraphInterpretation`  TEXT CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `paragraphIsSub` BOOL DEFAULT FALSE,
  `paragraphIsPartOfList` BOOL DEFAULT FALSE,
  PRIMARY KEY (`ruleId`, `sectionId`, `paragraphId`),
  FOREIGN KEY (ruleId, sectionId) REFERENCES ruleSections(ruleId, sectionId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `ruleParagraph`
--

INSERT INTO `ruleParagraph` 
	(`ruleId`, `sectionId`, `paragraphId`, `paragraphText`, `paragraphInterpretation`, `paragraphIsSub`, `paragraphIsPartOfList`) 
VALUES
(1, '1', 1, 'Näitä sääntöjä noudatetaan Suomen Kennelliitto - Finska Kennelklubben ry:n (jäljempänä Kennelliitto) hyväksymissä koiranäyttelyissä. Ilmoittaessaan koiran näyttelyyn näytteilleasettaja sitoutuu noudattamaan näitä sääntöjä sekä näitä sääntöjä täydentäviä Kennelliiton näyttelynjärjestämisohjeita ja FCI:n ohjeita sekä suostuu siihen, että hänen ilmoittautumislomakkeessa antamansa henkilö – ja osoitetiedot saa julkaista ja antaa ulkopuolisille, ellei hän ole tätä osoitetietojen osalta erikseen kieltänyt.', NULL, FALSE, FALSE),
(1, '1', 2, 'Näyttelystä on ilmoitettava vähintään kaksi kuukautta ennen sen toimeenpanemista Kennelliiton julkaisussa Koiramme-Våra Hundar.', NULL, FALSE, FALSE),
(1, '2', 1, 'Näyttelyiden tarkoituksena on tarjota koiraharrastajille mahdollisuus kilpailla omistamiensa/ esittämiensä koirien kanssa.  Koiranäyttelyissä koiraharrastajalla on tilaisuus vertailla jalostustyön tuloksia ja arvioida rodun jalostusmateriaalia.', NULL, FALSE, FALSE),
(1, '2', 2, 'Koirien hyvinvoinnin on oltava koiranäyttelyissä aina etusijalla.', NULL, FALSE, FALSE),
(1, '3', 1, 'Näyttelyyn saavat osallistua FCI:n tunnustaman maan kenneljärjestössä rekisteröidyt FCI:n ja Pohjoismaisen Kennelunionin PKU:n hyväksymien rotujen koirat, jotka on tunnistusmerkitty Kennelliiton hyväksymällä tavalla ja täyttävät voimassa olevat Kennelliiton hyväksymät terveysmääräykset.  Kansainvälisissä näyttelyissä rodut, joita FCI ei ole hyväksynyt, sijoitetaan näyttelyluettelossa omaan osioonsa ja ne eivät osallistu ryhmäkilpailuihin.', NULL, FALSE, FALSE),
(1, '3', 2, 'Arvostelun aikana ei koiralla saa olla kuonokoppaa tai muuta vastaavaa hallintavälinettä.', NULL, FALSE, FALSE),
(1, '3', 3, 'Näyttelyyn ei saa osallistua', NULL, FALSE, FALSE),
(1, '3', 4, 'koira, jota ei ole rokotettu Kennelliiton rokotusmääräysten mukaan', NULL, TRUE, TRUE),
(1, '3', 5, 'sairas koira', NULL, TRUE, TRUE),
(1, '3', 6, 'kantava narttu 30 vuorokautta ennen laskettua aikaa (laskettu aika = 63 vrk ensimmäisestä astutuksesta) ja synnyttänyt narttu alle 75 vrk synnytyksen jälkeen', NULL, TRUE, TRUE),
(1, '3', 7, 'Suomen lain vastaisesti typistetyt koirat (erillinen luettelo roduista, joilla esiintyy ns. luonnontöpöhäntäisyyttä)', NULL, TRUE, TRUE),
(1, '3', 8, 'vaarallisen vihainen koira ', NULL, TRUE, TRUE),
(1, '3', 9, 'koira, joka on saanut näyttelyssä kolme kertaa laatumaininnan \”hylätty\” käyttäytymisen takia', NULL, TRUE, TRUE),
(1, '3', 10,'koira, jolle on tehty jokin toimenpide rotumääritelmän mukaan tai muuten viaksi katsottavan ominaisuuden korjaamiseksi', NULL, TRUE, TRUE),
(1, '3', 11,'koira, jonka karvapeite on värjätty tai joka on trimmattu rotumääritelmän vastaisesti, pyrkimyksenä salata esim. pitkäkarvaisuutta tai todellista karvanlaatua', NULL, TRUE, TRUE),
(1, '3', 12,'koiran karvapeitteen, kirsun ja ihon käsitteleminen sellaisilla aineilla, jotka vaikuttavat väriin, muotoon ja rakenteeseen on kielletty.', NULL, TRUE, TRUE),
(1, '3', 13,'yleisen antidoping-säännön vastainen koira (liite 1)', NULL, TRUE, TRUE),
(1, '3', 14,'Sääntöjen vastaisen menettelyn tutkimiseksi on näyttelytoimikunnan valtuuttamalla henkilöllä oikeus ottaa koirista tarvittavia näytteitä näyttelyn aikana tai viiden vuorokauden kuluessa näyttelyn päättymisestä.', NULL, FALSE, FALSE),
(1, '3', 15,'Näyttelyyn osallistumisoikeutta ei ole', NULL, FALSE, FALSE),
(1, '3', 16,'koiralla, jonka omistajalla tai yhdelläkin omistajista on Kennelliiton kurinpitolautakunnan lisäseuraamuksena määräämä kielto tai Kennelliiton hallituksen määräämä tilapäinen kielto osallistua näyttelyihin näytteilleasettajana tai esittäjänä', NULL, TRUE, TRUE),
(1, '3', 17,'kasvattajaryhmällä, jonka kasvattajalla tai yhdelläkin kasvattajisa on Kennelliiton kurinpitolautakunnan lisäseuraamuksena määräämä kielto tai Kennelliiton hallituksen määräämä tilapäinen kielto osallistua näyttelyihin näytteilleasettajana tai esittäjänä', NULL, TRUE, TRUE),
(1, '3.1', 1, 'Näyttelyssä noudatetaan kulloinkin voimassa olevaa Kennelliiton yleistä jääviyssääntöä.', NULL, FALSE, FALSE),
(1, '3.2', 1, 'Näyttelyn eläinlääkäri voi tarkastaa koiria ja todetessaan koiran sairaaksi, hänellä on oikeus poistaa se näyttelystä. Eläinlääkäri voi myös ottaa koirista näytteitä näyttelyn aikana tai viiden vuorokauden kuluessa näyttelyn päättymisestä.', NULL, FALSE, FALSE),
(1, '4', 1, 'Ilmoittautuminen on tehtävä joko postitse tai sähköisesti Kennelliiton hyväksymällä lomakkeella, joka on maksuineen toimitettava näyttelytoimikunnalle ennen ilmoittautumisajan päättymistä. Sekä maksupäivän että kirjeen postileiman päiväyksen on oltava viimeistään ilmoittautumisajan päättymispäivä.', NULL, FALSE, FALSE),
(1, '4', 2, 'Koira on ilmoitettava näyttelyyn sillä nimellä ja sen rotuisena, jolla se on rekisteröity. Se on ilmoitettava laatuarvosteluluokkaan, johon se on oikeutettu osallistumaan.', NULL, FALSE, FALSE),
(1, '4', 3, 'Ilmoittautumisajan päättymisen jälkeen koiraa ei voida siirtää toiseen luokkaan (ellei kysymyksessä ole järjestäjästä johtuva virhe).', NULL, FALSE, FALSE),
(1, '4', 4, 'Jos koirasta on ilmoitettaessa annettu vääriä tietoja, koira voidaan sulkea näyttelystä ja mitätöidä sille jo mahdollisesti annetut tulokset.', NULL, FALSE, FALSE),
(1, '5', 1, 'Ilmoittautumismaksu palautetaan näytteilleasettajan niin halutessa, jos', NULL, FALSE, FALSE),
(1, '5', 2, 'näyttely peruutetaan', NULL, TRUE, TRUE),
(1, '5', 3, 'ilmoittautuminen peruutetaan tuomarimuutoksen vuoksi, ellei näyttelytoimikunta ole etukäteen ennen ensimmäisen ilmoittautumisajan päättymistä ilmoittanut rodulle varatuomaria näyttelyn virallisessa tiedotteessa (Koiramme-Våra hundar)', NULL, TRUE, TRUE),
(1, '5', 4, 'näyttelyilmoittautuminen on myöhästynyt', NULL, TRUE, TRUE),
(1, '5', 5, 'näyttelyyn ilmoitetun koiran kasvattaja kutsutaan kyseisen rodun tuomariksi ilmoittautumisajan päätyttyä ', NULL, TRUE, TRUE),
(1, '5', 6, 'Ilmoittautumismaksua ei palauteta, jos', NULL, FALSE, FALSE),
(1, '5', 7, 'näyttelyyn ilmoitettua koiraa ei ole rokotettu tai tunnistusmerkitty Kennelliiton määräysten mukaisesti', NULL, TRUE, TRUE),
(1, '5', 8, 'näyttelyyn ilmoitettu koira tai sen omistaja sairastuu', NULL, TRUE, TRUE),
(1, '5', 9, 'näyttely peruutetaan force majeure -syystä (yleisötapahtumien kieltäminen viranomaisten toimesta, liikennelakko, koirien terveystilanne jne.)', NULL, TRUE, TRUE),
(1, '5', 10,'Näyttelytoimikunnalla on oikeus periä ilmoittautumismaksun palauttamisesta aiheutuvat pankki- ja käsittelykulut. ', NULL, FALSE, FALSE),
(1, '6', 1, 'Näytteilleasettajan tulee huolehtia koiransa hyvinvoinnista ja hyvästä kohtelusta.', NULL, FALSE, FALSE),
(1, '6', 2, 'Näytteilleasettaja vastaa esittämiensä/omistamiensa koirien näyttelyssä mahdollisesti aiheuttamista vahingoista.', NULL, FALSE, FALSE),
(1, '6', 3, 'Näytteilleasettaja ei saa puhutella arvostelevaa tuomaria näyttelypaikalla ennen arvostelua eikä arvostelun aikana ilman pakottavaa syytä.', NULL, FALSE, FALSE),
(1, '6', 4, 'Näytteilleasettaja ei saa häiritä eikä moittia tuomaria tai muuten käyttäytyä näyttelypaikalla sopimattomasti tai hyvän tavan vastaisesti.', NULL, FALSE, FALSE),
(1, '7', 1, 'Näyttelynjärjestäjän pitää ottaa ryhmätapaturmavakuutus tuomareille ja kehätoimitsijoille sekä vastuuvakuutus, joka kattaa sen osan korvausvastuusta, joka näyttelyiden järjestämisestä voi syntyä yleisöä, toimihenkilöä tai ulkopuolista kohdanneesta henkilö- tai esinevahingosta. ', NULL, FALSE, FALSE),
(1, '8', 1, 'Arvostelevan tuomarin on oltava Suomen Kennelliiton hyväksymä ulkomuototuomari.', NULL, FALSE, FALSE),
(1, '9', 1, 'Ulkomuototuomari antaa jokaisesta arvostelemastaan koirasta kirjallisen lausunnon Kennelliiton lomakkeella. Lomakkeen jäljennös annetaan näytteilleasettajalle.', NULL, FALSE, FALSE),
(1, '9', 2, 'Tuomari voi niin harkitessaan hyväksyä vain Kennelliiton vahvistaman eläinlääkärintodistuksen ja huomioida sen arvostelussaan, jos koiralla on näyttelyarvosteluun vaikuttava vamma (esim. nikamavika hännässä tai hammaspuutos). Esitetystä todistuksesta on tehtävä merkintä arvostelulomakkeeseen.', NULL, FALSE, FALSE),
(1, '9', 3, 'Koiraa ei saa häiritä sitä arvosteltaessa eikä pyrkiä huonontamaan sen kilpailumahdollisuuksia.', NULL, FALSE, FALSE),
(1, '9', 4, 'Koiran esiintymistä ei saa yrittää parantaa kehän sisä- tai ulkopuolella arvostelua häiritsevästi. Ulkomuototuomarin tai kehätoimitsijan tulee puuttua kehän sisä- tai ulkopuolella tapahtuvaan arvostelua häiritsevään toimintaan. ', NULL, FALSE, FALSE),
(1, '9', 5, 'Arvostelusta myöhästynyt koira voi saada ainoastaan laatuarvostelun.', NULL, FALSE, FALSE),
(1, '9', 6, 'Kun koira on tuotu kehään mittausta ja/tai laatuarvostelua varten, se on esitettävä kaikissa niissä kilpailuluokissa, joihin sen saamat palkinnot oikeuttavat sen osallistumaan ellei näyttelytoimikunta ole antanut koiralle lupaa poistua ennen näyttelyn päättymistä.', NULL, FALSE, FALSE),
(1, '10', 1, 'Koirat arvostellaan luokittain näyttelysäännön mukaisessa järjestyksessä. Koirista annetaan kirjallinen laatuarvostelu.', NULL, FALSE, FALSE),
(1, '10.1', 1, 'Laatuarvostelussa annetaan niin monta eri laatumainintaa, kuin koirien laatu edellyttää.', NULL, FALSE, FALSE),
(1, '10.1', 2, 'Laatumaininnat:', NULL, FALSE, FALSE),
(1, '10.1', 3, 'Tuomarin antaman laatuarvostelun tulee vastata seuraavia määritelmiä:', NULL, FALSE, FALSE),
(1, '10.1', 4, 'ERINOMAINEN voidaan antaa koiralle, joka on hyvin lähellä rotumääritelmän ihannetta, joka esitetään erinomaisessa kunnossa, jolla tasapainoinen luonne, joka on korkealuokkainen ja joka on olemukseltaan erinomainen. Sen ulkomuodolliset ansiot ovat suuret ja virheet vähäiset ja sen tulee omata sukupuolelleen tyypilliset piirteet.', NULL, FALSE, FALSE),
(1, '10.1', 5, 'ERITTÄIN HYVÄ voidaan antaa koiralle, joka omaa rodulle tyypilliset piirteet, jolla on tasapainoinen rakenne, ja joka on hyvässä kunnossa. Muutama vähäinen virhe voidaan sallia, mutta ei rakenteellisia virheitä. Tämä laatumaininta voidaan antaa vain tasokkaalle koiralle.', NULL, FALSE, FALSE),
(1, '10.1', 6, 'HYVÄ annetaan koiralle, joka on rodulleen tyypillinen, mutta sillä on selkeitä virheitä.', NULL, FALSE, FALSE),
(1, '10.1', 7, 'TYYDYTTÄVÄ tulee antaa koiralle, joka vastaa rotuaan ilman yleisesti hyväksyttyjä rodun piirteitä, tai jonka fyysisessä kunnossa on toivomisen varaa.', NULL, FALSE, FALSE),
(1, '10.1', 8, 'HYLÄTTY tulee antaa koiralle, joka ei rakenteeltaan vastaa rotumääritelmää, jonka käytös ei ole rotumääritelmän mukainen tai se on selvästi vihainen, jolla on sääntöjen vastainen kivespuutos tai kivesvika, hammaspuutoksia tai poikkeavuutta purennassa tai leuoissa, jonka väritys tai karvapeite on puutteellinen tai joka osoittaa selvästi merkkejä albinismista. ', NULL, FALSE, FALSE),
(1, '10.1', 9, 'Tämä laatumaininta voidaan antaa myös koiralle, joka ei vaikuta terveeltä. Sen lisäksi se voidaan antaa koiralle, jolla on rotumääritelmän vastainen hylkäävä virhe.', NULL, FALSE, FALSE),
(1, '10.1', 10,'Koirat, joille ei voida antaa mitään edellä mainituista laatumaininnoista poistetaan kehästä maininnalla:', NULL, FALSE, FALSE),
(1, '10.1', 11,'EI VOIDA ARVOSTELLA: Tämä maininta annetaan koiralle, joka ei liiku, hyppii jatkuvasti esittäjänsä ympärillä tai pyrkii ulos kehästä, jonka liikkeitä on mahdoton arvostella tai jos koira jatkuvasti välttelee tuomarin käsittelyä ja tekee mahdottomaksi tarkastaa purennan ja hampaat, rakenteen, hännän tai kivekset, tai jos on havaittavissa jälkiä toimenpiteistä tai käsittelystä, jotka näyttävät vilpin yritykseltä tai tuomarilla on syytä epäillä, että koiralla olevaa vikaa on korjailtu (esim. silmäluomia, korvia tai häntää). Syy, miksi koiraa ei voida arvostella, on kirjattava arvosteluun.', NULL, FALSE, FALSE),
(1, '10.2', 1, 'Kilpailuarvostelussa tuomari sijoittaa luokittain erinomainen ja erittäin hyvä laatumaininnalla palkitut neljä (4) parasta koiraa paremmuusjärjestykseen. Nämä saavat merkinnän sijoituksesta arvosteluunsa.', NULL, FALSE, FALSE),
(1, '10.2', 2, 'Tuomari voi harkintansa mukaan antaa sekä kilpailuarvostelussa sijoittuneille että muille luokassa kilpailleille, erinomaisella palkituille koirille SERTIFIKAATIN ARVOISEN (SA), joka oikeuttaa koiran osallistumaan paras uros- ja paras narttu -luokkaan.', NULL, FALSE, FALSE),
(1, '11', 1, 'Koira voi kasvattaja – ja jalostusluokkaa lukuun ottamatta kilpailla vain yhdessä laatuarvosteluluokassa, joka ilmoittajalla on mahdollisuus valita sääntöjen mukaan.', NULL, FALSE, FALSE),
(1, '11', 2, 'Urokset ja nartut arvostellaan erikseen lukuun ottamatta rotunsa paras- kasvattaja- ja jalostusluokkia, ryhmäkilpailuja ja Best in Show -kilpailua.', NULL, FALSE, FALSE),
(1, '11', 3, 'Koira voidaan ilmoittaa vain yhteen seuraavista luokista (a-h) ', NULL, FALSE, FALSE),
(1, '11.a', 1, 'Kilpailuarvostelu koirille, jotka viimeistään näyttelypäivänä täyttävät viisi kuukautta, mutta eivät ole täyttäneet seitsemää kuukautta. Tuomari voi antaa kunniapalkinnon pennuille, jotka hän katsoo sen arvoisiksi. Pikkupentuluokka voidaan järjestää vain rotujärjestön / rotua harrastavan yhdistyksen erikoisnäyttelyissä.', NULL, FALSE, FALSE),
(1, '11.b', 1, 'Kilpailuarvostelu koirille, jotka viimeistään näyttelypäivänä täyttävät seitsemän kuukautta, mutta eivät ole täyttäneet yhdeksää kuukautta. Tuomari voi antaa kunniapalkinnon pennuille, jotka hän katsoo sen arvoisiksi.', NULL, FALSE, FALSE),
(1, '11.b', 2, 'Paras kunniapalkinnon saanut uros- ja narttupentu osallistuu rotunsa paras pentu -kilpailuun.', NULL, FALSE, FALSE),
(1, '11.b', 3, 'Pentuluokat ovat epävirallisia ja järjestetään vain näyttelytoimikunnan niin halutessa.', NULL, FALSE, FALSE),
(1, '11.b', 4, 'Best in Show pentu -kilpailu voidaan järjestää vain erikoisnäyttelyissä.', NULL, FALSE, FALSE),
(1, '11.c', 1, 'Laatuarvostelu koirille, jotka viimeistään näyttelypäivänä täyttävät yhdeksän (9) kuukautta, mutta eivät ole täyttäneet kahdeksaatoista (18) kuukautta.', NULL, FALSE, FALSE),
(1, '11.d', 1, 'Laatuarvostelu koirille, jotka viimeistään näyttelypäivänä täyttävät viisitoista (15) kuukautta, mutta eivät ole täyttäneet kahtakymmentäneljää (24) kuukautta.', NULL, FALSE, FALSE),
(1, '11.e', 1, 'Laatuarvostelu koirille, jotka viimeistään näyttelypäivänä täyttävät viisitoista (15) kuukautta. Luokassa ei ole yläikärajaa.', NULL, FALSE, FALSE),
(1, '11.f', 1, 'Laatuarvostelu koirille, jotka viimeistään näyttelypäivänä täyttävät viisitoista (15) kuukautta.', NULL, FALSE, FALSE),
(1, '11.f', 2, 'Kansainvälisissä näyttelyissä käyttöluokkaan voi ilmoittaa vain rodun, jonka FCI määrittelee käyttökoiraroduksi tai jolle FCI on erikseen antanut osallistumisoikeuden. (liite 3, lista roduista).', NULL, FALSE, FALSE),
(1, '11.f', 3, 'Näillä roduilla sekä kansainvälisissä että kansallisissa näyttelyissä osallistumiseen oikeuttava koetulos on vähintään Suomen tai kansainvälisen muotovalion arvoon vaadittava koetulos tai koetulokset.', NULL, FALSE, FALSE),
(1, '11.f', 4, 'Vinttikoirien käyttöluokkaan osallistumisen ehtona on voimassa oleva kilpailukirja. Lisäksi koiran on täytynyt osallistua vähintään kahteen (2) kansainväliseen kilpailuun (CACIL) ja sen on molemmissa kilpailuissa oltava sijoittunut parhaaseen puolikkaaseen osallistujamäärästä. Maastojuoksukilpailuissa koiran on täytynyt saavuttaa vähintään 2/3 enimmäispistemäärästä. Kilpailutulosten välillä tulee olla vähintään yksi vuosi ja yksi päivä. Ilmoitettaessa vinttikoira käyttöluokkaan on kopio koiran kilpailukirjasta oheistettava näyttelytoimikunnalle.', NULL, FALSE, FALSE),
(1, '11.f', 5, 'Kansallisissa näyttelyissä ne rodut, jotka voivat saavuttaa Suomessa käyttövalion arvon, mutta eivät kuulu FCI:n määrittelemiin käyttökoirarotuihin, voivat osallistua käyttöluokkaan saavutettuaan käyttövalion arvon.', NULL, FALSE, FALSE),
(1, '11.f', 6, 'Poikkeuksena ovat alaskanmalamuutti, grönlanninkoira, samojedinkoira ja siperianhusky, joilta vaaditaan hyväksytty tulos rodunomaisesta kokeesta.', NULL, FALSE, FALSE),
(1, '11.f', 7, 'Luonnetestitulos ei oikeuta osallistumaan käyttöluokkaan.', NULL, FALSE, FALSE),
(1, '11.g', 1, 'Laatuarvostelu koirille, jotka viimeistään näyttelypäivänä täyttävät viisitoista (15) kuukautta ja ovat jonkin FCI:n tunnustaman kenneljärjestön tai kansainvälisiä muotovalioita. Suomen muotovalio on ilmoitettava aina valioluokkaan, ellei koiralla ole oikeutta osallistua käyttö- tai veteraaniluokkaan.', NULL, FALSE, FALSE),
(1, '11.h', 1, 'Laatuarvostelu koirille, jotka viimeistään näyttelypäivänä täyttävät kahdeksan (8) vuotta.', NULL, FALSE, FALSE),
(1, '11.h', 2, 'Rotunsa paras veteraani, joka on palkittu laatumaininnalla erinomainen, saa jatkaa edelleen kilpailemista Best in Show veteraanin arvosta.', NULL, FALSE, FALSE),
(1, '11.i', 1, 'Tähän luokkaan ovat oikeutettuja osallistumaan koirat, jotka on (sijoittuneet juniori-, nuorten-, avoin-, valio-, käyttö- tai veteraaniluokassa neljän parhaan joukkoon laatumaininnalla erinomainen ja) palkittu sertifikaatin arvoisella (SA). ', NULL, FALSE, FALSE),
(1, '11.i', 2, 'Tuomari voi antaa sertifikaatin parhaalle siihen oikeutetulle sertifikaatin arvoisella (SA) palkitulle koiralle, jolla ei ole Suomen muotovalion arvoon oikeuttavia näyttelytuloksia. Varasertifikaatin voi saada toiseksi paras sertifikaatin arvoisella (SA) palkittu koira, jolla ei ole Suomen muotovalion arvoon oikeuttavia näyttelytuloksia.', NULL, FALSE, FALSE),
(1, '11.i', 3, 'Tuomari voi niin harkitessaan esittää CACIBia parhaaksi katsomalleen siihen oikeutetulle koiralle ja varaCACIBia toiseksi parhaaksi katsomalleen siihen oikeutetulle koiralle, jotka ovat kilpailleet nuortenluokassa, avoimessa luokassa, käyttöluokassa tai valioluokassa. ', NULL, FALSE, FALSE),
(1, '11.j', 1, 'Rodun parhaan valintaan osallistuvat paras uros ja paras narttu.', NULL, FALSE, FALSE),
(1, '11.j', 2, 'Rotunsa paras koira osallistuu ryhmäkilpailuun.', NULL, FALSE, FALSE),
(1, '11.k', 1, 'Kasvattajaluokka on laatuarvostelu, jossa kilpailee neljän samanrotuisen koiran muodostama ryhmä. Koirien on oltava saman kasvattajan kasvattamia tai samalle FCI:n vahvistamalle kennelnimelle rekisteröityjä. Lisäksi koirien on oltava palkittu laatumaininnalla erinomainen tai erittäin hyvä tässä näyttelyssä.', NULL, FALSE, FALSE),
(1, '11.k', 2, 'Kasvattaja saa kilpailla yhdessä näyttelyssä vain yhdellä ryhmällä rotua kohti.', NULL, FALSE, FALSE),
(1, '11.k', 3, 'Jos tuomari katsoo ryhmän olevan riittävän tasalaatuinen ja korkeatasoinen, hän voi antaa kunniapalkinnon.', NULL, FALSE, FALSE),
(1, '11.k', 4, 'Kasvattajaluokan kilpailuarvostelu (KAK). Tuomari sijoittaa neljä (4) kasvattajaryhmää paremmuusjärjestykseen. Mikäli rodun paras ryhmä on saanut kunniapalkinnon, se osallistuu Best in Show -kasvattajaryhmän valintaan.', NULL, FALSE, FALSE),
(1, '11.1', 1, 'Rodun paras kunniapalkinnolla palkittu kasvattajaryhmä osallistuu näyttelyn parhaan kasvattajaryhmän valintaan. Tuomari sijoittaa neljä (4) parasta ryhmää paremmuusjärjestykseen.', NULL, FALSE, FALSE),
(1, '11.m', 1, 'Jälkeläisluokka on laatuarvostelu, jossa uros tai narttu kilpailee neljän samanrotuisen jälkeläisensä muodostamalla ryhmällä. Jälkeläisten tulee olla palkittu laatumaininnalla erinomainen tai erittäin hyvä tässä näyttelyssä. Urosta tai narttua ei tarvitse ilmoittaa muihin luokkiin, mutta se tulee esittää jälkeläisryhmänsä kanssa.', NULL, FALSE, FALSE),
(1, '11.m', 2, 'Jälkeläisluokka voidaan järjestää vain rotujärjestön/rotua harrastavan yhdistyksen erikoisnäyttelyissä.', NULL, FALSE, FALSE),
(1, '11.m', 3, 'Jos tuomari katsoo ryhmän olevan riittävän tasalaatuinen ja korkeatasoinen, hän voi antaa kunniapalkinnon.', NULL, FALSE, FALSE),
(1, '11.m', 4, 'Jälkeläisluokan kilpailuarvostelu (JÄK). Tuomari sijoittaa neljä (4) jälkeläisryhmää paremmuusjärjestykseen. Mikäli rodun paras ryhmä on saanut kunniapalkinnon, se osallistuu Best in Show -jälkeläisryhmän valintaan.', NULL, FALSE, FALSE),
(1, '11.n', 1, 'Rodun paras kunniapalkinnolla palkittu jälkeläisryhmä osallistuu näyttelyn parhaan jälkeläisryhmän valintaan. Tuomari sijoittaa neljä (4) parasta ryhmää paremmuusjärjestykseen. BIS-JÄL voidaan järjestää vain rotujärjestön/rotua harrastavan yhdistyksen erikoisnäyttelyissä.', NULL, FALSE, FALSE),
(1, '11.o', 1, 'Kilpailuun osallistuvat rotunsa parhaat veteraaniluokissa kilpailleet koirat. Tuomari sijoittaa neljä (4) parasta koiraa paremmuusjärjestykseen.', NULL, FALSE, FALSE),
(1, '11.p', 1, 'Kilpailuun osallistuvat rotunsa parhaat koirat roturyhmittäin. Tuomari sijoittaa neljä (4) parasta koiraa paremmuusjärjestykseen.', NULL, FALSE, FALSE),
(1, '11.q', 1, 'Best in Show valitaan ryhmien voittajista. Tuomari sijoittaa neljä (4) parasta koiraa paremmuusjärjestykseen.', NULL, FALSE, FALSE),
(1, '12', 1, 'Laatuarvostelun tulos osoitetaan seuraavin värein:', NULL, FALSE, FALSE),
(1, '12', 2, 'erinomainen		punainen', NULL, TRUE, TRUE),
(1, '12', 3, 'erittäin hyvä		sininen', NULL, TRUE, TRUE),
(1, '12', 4, 'hyvä			keltainen', NULL, TRUE, TRUE),
(1, '12', 5, 'tyydyttävä		vihreä', NULL, TRUE, TRUE),
(1, '12', 6, 'hylkäävä			harmaa', NULL, TRUE, TRUE),
(1, '12', 7, 'ei voida arvostella	ruskea', NULL, TRUE, TRUE),
(1, '12', 8, 'sertifikaatin arvoinen	vaaleanpunainen', NULL, TRUE, TRUE),
(1, '12', 9, 'Kilpailuarvostelun sijoitukset osoitetaan seuraavin värein:', NULL, FALSE, FALSE),
(1, '12', 10,'1. punainen', NULL, TRUE, TRUE),
(1, '12', 11,'2. sininen', NULL, TRUE, TRUE),
(1, '12', 12,'3. keltainen', NULL, TRUE, TRUE),
(1, '12', 13,'4. vihreä', NULL, TRUE, TRUE),
(1, '12', 14,'Näyttelyssä jaettavat palkintoruusukkeet ja nauhat:', NULL, FALSE, FALSE),
(1, '12', 15,'sertifikaatti	sinivalkoinen', NULL, TRUE, TRUE),
(1, '12', 16,'varasertifikaatti	vaaleansininen', NULL, TRUE, TRUE),
(1, '12', 17,'CACIB		valkoinen', NULL, TRUE, TRUE),
(1, '12', 18,'vara-CACIB	oranssi', NULL, TRUE, TRUE),
(1, '12', 19,'ROP		punakeltainen', NULL, TRUE, TRUE),
(1, '12', 20,'VSP		valkovihreä ', NULL, TRUE, TRUE),
(1, '12', 21,'kunniapalkinto	lila', NULL, TRUE, TRUE),
(1, '12', 22,'Suomen muotovalio punavihreä', NULL, TRUE, TRUE),
(1, '13', 1, 'Tuomarin päätös on lopullinen, eikä siitä voi valittaa. Tuomari ei voi muuttaa koirasta antamaansa arvostelua, ellei ole sattunut järjestely- tai muuta siihen verrattavaa virhettä (esim. koira on arvosteltu luokassa, johon sillä ei ole ollut oikeutta osallistua). Muutos on suoritettava yhdessä näyttelytoimikunnan jäsenen kanssa.', NULL, FALSE, FALSE),
(1, '13', 2, 'Mikäli kyseessä on merkintävirhe, joka voidaan tulosten perusteella oikaista, voidaan se tehdä myös Kennelliitossa tulosten tarkastuksen yhteydessä.', NULL, FALSE, FALSE),
(1, '13', 3, 'Tuomarin arvostelusta voi valittaa ainoastaan, mikäli tuomari on toiminut näiden sääntöjen tai hyvän tavan vastaisesti.', NULL, FALSE, FALSE),
(1, '14', 1, 'Koiranäyttelysääntöjä täydentävät Kennelliiton hallituksen antamat koiranäyttelyiden järjestämisohjeet, ulkomuototuomareiden toimintaohjeet, Kennelliiton antamat muut säännöt ja ohjeet sekä sen käyttöönottamat FCI:n ohjeet.', NULL, FALSE, FALSE),
(1, '14', 2, 'Kennelliiton hallitus voi pakottavista syistä rajoittaa näyttelyyn osallistumista tai antaa muita näyttelyn toimeenpanoa koskevia erikoismääräyksiä.', NULL, FALSE, FALSE),
(1, '15', 1, 'Valitukset tehdään Kennelliiton vahvistaman muutoksenhakumenettelyn mukaisesti. (liite 4)', NULL, FALSE, FALSE),
(1, '16', 1, 'Nämä säännöt ovat voimassa 1.1.2017 - 31.12.2021.', NULL, FALSE, FALSE),
