DROP TABLE IF EXISTS `ruleSections`;

--
-- Table structure for table `ruleSections`
--

CREATE TABLE IF NOT EXISTS `ruleSections` (
  `ruleId` int(3) NOT NULL,
  `sectionId` varchar(10) NOT NULL,
  `parentSection` varchar(10) DEFAULT NULL,
  `sectionHeader` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`ruleId`, `sectionId`),
  FOREIGN KEY (ruleId) REFERENCES rules(ruleId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `ruleSections`
--

INSERT INTO `ruleSections` 
	(`ruleId`, `sectionId`, `parentSection`, `sectionHeader`) 
VALUES
	(1, '1', NULL, ' Yleistä'),
	(1, '2', NULL, ' Näyttelyn tarkoitus'),
	(1, '3', NULL, ' Osallistumisoikeus'),
	(1, '3.1', 3,  'Jääviys'),
	(1, '3.2', 3,  'Terveysmääräykset'),
	(1, '4', NULL, ' Ilmoittautuminen'),
	(1, '5', NULL, ' Ilmoittautumisen peruuttaminen '),
	(1, '6', NULL, ' Näytteilleasettajaa koskevia määräyksiä'),
	(1, '7', NULL, ' Vastuuvakuutus'),
	(1, '8', NULL, ' Ulkomuototuomarit'),
	(1, '9', NULL, ' Koirien arvostelu'),
	(1, '10', NULL, ' Arvosteluperusteet'),
	(1, '10.1', '10', ' Laatuarvostelu'),
	(1, '10.2', '10', ' Kilpailuarvoste'),
	(1, '11', NULL, ' Arvosteluluokat'),
	(1, '11.a', '11', 'Pikkupentuluokka (BABY)'),
	(1, '11.b', '11', 'Pentuluokka (PEK)'),
	(1, '11.c', '11', 'Junioriluokka (JUN)'),
	(1, '11.d', '11', 'Nuorten luokka (NUO)'),
	(1, '11.e', '11', 'Avoin luokka (AVO)'),
	(1, '11.f', '11', 'Käyttöluokka (KÄY)'),
	(1, '11.g', '11', 'Valioluokka (VAL)'),
	(1, '11.h', '11', 'Veteraaniluokka (VET)'),
	(1, '11.i', '11', 'Paras uros-/paras narttuluokka (PU/PN)'),
	(1, '11.j', '11', 'Rodun (ROP) ja vastakkaisen sukupuolen paras (VSP)'),
	(1, '11.k', '11', 'Kasvattajaluokka (KAS)'),
	(1, '11.l', '11', 'Best in Show kasvattajaluokka (BIS-KAS)'),
	(1, '11.m', '11', 'Jälkeläisluokka (JÄL)'),
	(1, '11.n', '11', 'Best in Show jälkeläisluokka (BIS-JÄL)'),
	(1, '11.o', '11', 'Best in Show veteraani -kilpailu (BIS-VET)'),
	(1, '11.p', '11', 'Ryhmän paras -kilpailu (RYP)'),
	(1, '11.q', '11', 'Best in Show (BIS)'),
	(1, '12', NULL, ' Palkintoa osoittavat värit'),
	(1, '13', NULL, ' Arvostelun muuttaminen'),
	(1, '14', NULL, ' Muut ohjeet'),
	(1, '15', NULL, ' Valitukset'),
	(1, '16', NULL, ' Voimassaolo'),

	(2, 'A', NULL, 'Näyttelysääntöjä täydentävät ohjeet'),
	(2, 'A.1', 'A', 'Yleistä'),
	(2, 'A.2', 'A', 'Osallistumisoikeus'),
	(2, 'A.3', 'A', 'Ilmoittautuminen'),
	(2, 'A.3.1', 'A.3', 'Yleistä'),
	(2, 'A.3.2', 'A.3', 'Luokat ja niiden vaihtaminen'),
	(2, 'A.3.3', 'A.3', 'Maksut ja maksupalautukset'),
	(2, 'A.3.4', 'A.3', 'Ilmoittautumisen peruuttaminen'),
	(2, 'A.4', 'A', 'Sertifikaatti'),
	(2, 'A.5', 'A', 'Kansainvälinen sertifikaatti l. CACIB'),
	(2, 'A.6', 'A', 'Siirto rodusta tai rotumuunnoksesta toiseen'),
	(2, 'A.7', 'A', 'Kivesvikaisuus ja sen toteaminen'),
	(2, 'A.8', 'A', 'Sekarotuisuus ja sen toteaminen'),
	(2, 'A.9', 'A', 'Viaksi katsottavan tai muun ominaisuuden korjaaminen tai muuttaminen'),
	(2, 'A.10', 'A', 'Koiran käyttäytymisestä näyttelyssä tehtävät ilmoitukset, niiden käsittely ja seuraukset'),
	(2, 'A.10.1', 'A.10', 'Toiminta ja seuraukset laatuarvostelussa'),
	(2, 'A.10.2', 'A.10', 'Toiminta ja seuraukset laatuarvostelun ulkopuolella'),
	(2, 'A.10.3', 'A.10', 'Ilmoitukset'),
	(2, 'A.10.4', 'A.10', 'Ilmoitusmenettely'),
	(2, 'A.10.5', 'A.10', 'Päätöksenteko'),
	(2, 'A.11', 'A', 'Näytteilleasettajaa koskevia määräyksiä'),
	(2, 'A.12', 'A', 'Ulkomuototuomarit'),
	(2, 'A.12.1', 'A.12', 'Ulkomuototuomarikohtainen koiramäärä'),
	(2, 'A.12.2', 'A.12', 'Ulkomuototuomarimuutokset'),
	(2, 'A.12.3', 'A.12', 'Ulkomuototuomarin oikeudet arvostella ryhmäkilpailuja'),
	(2, 'A.12.4', 'A.12', 'Ulkomuototuomarin esteellisyys'),
	(2, 'A.13', 'A', 'Koirien arvostelu'),
	(2, 'A.14', 'A', 'Arvosteluluokat'),
	(2, 'A.15', 'A', 'Palkinnot'),
	(2, 'A.16', 'A', 'Muut ohjeet'),
	(2, 'A.17', 'A', 'Valitukset'),
	(2, 'B', NULL, 'Näyttelyiden järjestämisohje'),
	(2, 'B.1', 'B', 'Järjestämisoikeus'),
	(2, 'B.1.1', 'B.1', 'Suomen Kennelliitto'),
	(2, 'B.1.2', 'B.1', 'Kennelpiirit'),
	(2, 'B.1.3', 'B.1', 'Kennelpiirien jäsenyhdistykset'),
	(2, 'B.1.4', 'B.1', 'Rotujärjestöt ja rotua harrastavat yhdistykset'),
	(2, 'B.1.5', 'B.1', 'Poikkeaminen kennelpiirien rajoista'),
	(2, 'B.2', 'B', 'Näyttelylajit'),
	(2, 'B.2.1', 'B.2', 'Kansainväliset näyttelyt'),
	(2, 'B.2.2', 'B.2', 'Pohjoismaiset näyttelyt'),
	(2, 'B.2.3', 'B.2', 'Kaikkien rotujen näyttelyt'),
	(2, 'B.2.4', 'B.2', 'Ryhmänäyttelyt'),
	(2, 'B.2.4.1', 'B.2.4', 'Vaihtoehto 1'),
	(2, 'B.2.4.2', 'B.2.4', 'Vaihtoehto 2'),
	(2, 'B.2.4.3', 'B.2.4', 'Vaihtoehto 3'),
	(2, 'B.2.4.4', 'B.2.4', 'Vaihtoehto 4'),
	(2, 'B.2.4.5', 'B.2.4', 'Vaihtoehto 5'),
	(2, 'B.2.5', 'B.2', 'Erikoisnäyttelyt'),
	(2, 'B.2.6', 'B.2', 'Tukinäyttelyt'),
	(2, 'B.3', 'B', 'Näyttelyiden hakumenettely'),
	(2, 'B.3.1', 'B.3', 'Yleistä'),
	(2, 'B.3.2', 'B.3', 'Kansainväliset ja kaikkien rotujen näyttelyt'),
	(2, 'B.3.3', 'B.3', 'Ryhmänäyttelyt'),
	(2, 'B.3.4', 'B.3', 'Erikoisnäyttelyt'),
	(2, 'B.3.5', 'B.3', 'Tukinäyttelyt'),
	(2, 'B.4', 'B', 'Näyttelyiden ajallinen sovittaminen'),
	(2, 'B.5', 'B', 'Tulosten toimittaminen'),
	(2, 'B.6', 'B', 'Näyttelymaksuosuus'),
	(2, 'B.7', 'B', 'Näyttelytoimikunta'),
	(2, 'B.7.1', 'B.7', 'Toimikunnan kokoonpano'),
	(2, 'B.7.2', 'B.7', 'Näyttelyn sihteeri'),
	(2, 'B.7.3', 'B.7', 'Näyttelyohjaaja'),
	(2, 'B.8', 'B', 'Näyttelypaikka'),
	(2, 'B.9', 'B', 'Näyttelystä tiedottaminen'),
	(2, 'B.9.1', 'B.9', 'Ilmoitus Koiramme -lehdessä'),
	(2, 'B.9.2', 'B.9', 'Tiedote'),
	(2, 'B.10', 'B', 'Ilmoittautumisten käsittely ja näyttelyluettelo'),
	(2, 'B.10.1', 'B.10', 'Ilmoittautumisten vastaanotto'),
	(2, 'B.10.2', 'B.10', 'Aikataulun laadinta'),
	(2, 'B.10.3', 'B.10', 'Kirjeet näytteilleasettajille'),
	(2, 'B.10.4', 'B.10', 'Näyttelyluettelo'),
	(2, 'B.11', 'B', 'Ulkomuototuomarit'),
	(2, 'B.11.1', 'B.11', 'Ulkomuototuomarilistan laadinta'),
	(2, 'B.11.2', 'B.11', 'Yhteydenpito ulkomuototuomareihin'),
	(2, 'B.11.3', 'B.11', 'Ulkomaisten ulkomuototuomareiden ohjaus'),
	(2, 'B.11.4', 'B.11', 'Harjoitusarvostelijat'),
	(2, 'B.12', 'B', 'Kehätoimitsijat'),
	(2, 'B.13', 'B', 'Eläinlääkäri'),
	(2, 'B.14', 'B', 'Kulukorvaukset ja niiden maksaminen'),
	(2, 'B.14.1', 'B.14', 'Matkakorvaus'),
	(2, 'B.14.2', 'B.14', 'Majoitus'),
	(2, 'B.14.3', 'B.14', 'Päiväraha'),
	(2, 'B.14.4', 'B.14', 'Muut määräykset'),
	(2, 'B.14.5', 'B.14', 'Muuta huomioitavaa'),
	(2, 'B.15', 'B', 'Kennelliiton neuvontapiste'),
	(2, 'B.16', 'B', 'Poikkeukset'),

	(3, '1', NULL, 'Kaikkia rotuja koskevat vaatimukset'),
	(3, '1.1', '1', 'Muotovalion arvo (FI MVA)'),
	(3, '1.2', '1', 'Agilityvalion arvo (FI AVA)'),
	(3, '1.3', '1', 'Hyppyvalion arvo (FI AVA-H)'),
	(3, '1.4', '1', 'Jäljestämisvalion arvo (FI JVA)'),
	(3, '1.5', '1', 'Koiratanssivalionarvo (FI KTV ja FI KTV-V)'),
	(3, '1.5.1', '1.5', 'Seuraaminen musiikin tahdissa (Heelwork to Music FI KTV)'),
	(3, '1.5.2', '1.5', 'Vapaaohjelma (Freestyle FI KTV-V)'),
	(3, '1.6', '1', 'Käyttövalion arvo (FI KVA)'),
	(3, '1.6.1', '1.6', 'Palveluskoirakokeiden käyttövalion arvo'),
	(3, '1.7', '1', 'Käyttövalion arvo (FI KVA-J)'),
	(3, '1.8', '1', 'Metsästysvalion arvo (FI KVA-L ja FI KVA-M)'),
	(3, '1.9', '1', 'Paimennusvalion arvo (FI PVA)'),
	(3, '1.10', '1', 'Rally-tokovalion arvo (FI RTVA)'),
	(3, '1.11', '1', 'Tottelevaisuusvalion arvo (FI TVA)'),
	(3, '1.12', '1', 'Vesipelastusvalion arvo (FI VPVA)'),
	(3, '1.13', '1', 'Vetovalion arvo (FI VVA)'),
	(3, '1.14', '1', 'Pohjoismaiden käyttövalion arvo (POHJ KVA)'),
	(3, '1.15', '1', 'Pohjoismaiden muotovalion arvo (POHJ MVA)'),
	(3, '1.16', '1', 'Erinäiset säännökset'),
	(3, '1.17', '1', 'Lyhenteiden selitykset'),

	(4, 'A', NULL, 'Yleinen valitusmenettely'),
	(4, 'A.1', 'A', 'Kokeet, kilpailut ja luonnetestit'),
	(4, 'A.1.1', 'A.1', 'Valitusaika, valitusmaksu ja jatkovalitukset '),
	(4, 'A.2', 'A', 'Näyttelyt'),
	(4, 'A.2.1', 'A.2', 'Valitusaika ja valitusmaksu'),
	(4, 'A.2.2', 'A.2', 'Jatkovalitukset'),
	(4, 'B', NULL, 'Oikaisuvaatimusmenettely'),

	(5, '1', NULL, 'Määritelmiä'),
	(5, '2', NULL, 'Salassapito'),
	(5, '3', NULL, 'Koiran suorituskykyyn vaikuttaminen'),
	(5, '4', NULL, 'Dopingnäytteiden ottamisen perusteet'),
	(5, '4.1', '4', 'Lakiperusteinen dopingvalvonta'),
	(5, '4.2', '4', 'Sattumanvarainen sekä koiran menestykseen perustuva dopingvalvonta'),
	(5, '4.3', '4', 'Poikkeavaan suoritukseen tai muuhun perusteltuun epäilyyn perustuva dopingvalvonta'),
	(5, '5', NULL, 'Dopingnäytteiden ottamista koskeva menettely'),
	(5, '6', NULL, 'Rangaistukset'),
	(5, '7', NULL, 'Näytteenoton ja tutkimuksen kustannukset'),
	(5, '8', NULL, 'Täydentävät ohjeet'),

	(6, '1', NULL, '§'),
	(6, '2', NULL, '§'),
	(6, '3', NULL, '§'),
	(6, '4', NULL, '§')
;
