DROP TABLE IF EXISTS `ruleParagraph`;

--
-- Table structure for table `ruleParagraph`
--

CREATE TABLE IF NOT EXISTS `ruleParagraph` (
  `ruleId` int(3) NOT NULL,
  `sectionId` varchar(10) NOT NULL,
  `paragraphId` int(3) NOT NULL,
  `paragraphText` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `paragraphInterpretation`  TEXT CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `paragraphIsSub` BOOL DEFAULT FALSE,
  `paragraphIsPartOfList` BOOL DEFAULT FALSE,
  PRIMARY KEY (`ruleId`, `sectionId`, `paragraphId`),
  FOREIGN KEY (ruleId, sectionId) REFERENCES ruleSections(ruleId, sectionId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `ruleParagraph`
--

INSERT INTO `ruleParagraph` 
	(`ruleId`, `sectionId`, `paragraphId`, `paragraphText`, `paragraphInterpretation`, `paragraphIsSub`, `paragraphIsPartOfList`) 
VALUES
(1, '1', 1, 'Näitä sääntöjä noudatetaan Suomen Kennelliitto - Finska Kennelklubben ry:n (jäljempänä Kennelliitto) hyväksymissä koiranäyttelyissä. Ilmoittaessaan koiran näyttelyyn näytteilleasettaja sitoutuu noudattamaan näitä sääntöjä sekä näitä sääntöjä täydentäviä Kennelliiton näyttelynjärjestämisohjeita ja FCI:n ohjeita sekä suostuu siihen, että hänen ilmoittautumislomakkeessa antamansa henkilö – ja osoitetiedot saa julkaista ja antaa ulkopuolisille, ellei hän ole tätä osoitetietojen osalta erikseen kieltänyt.', NULL, FALSE, FALSE),
(1, '1', 2, 'Näyttelystä on ilmoitettava vähintään kaksi kuukautta ennen sen toimeenpanemista Kennelliiton julkaisussa Koiramme-Våra Hundar.', NULL, FALSE, FALSE),
(1, '2', 1, 'Näyttelyiden tarkoituksena on tarjota koiraharrastajille mahdollisuus kilpailla omistamiensa/ esittämiensä koirien kanssa.  Koiranäyttelyissä koiraharrastajalla on tilaisuus vertailla jalostustyön tuloksia ja arvioida rodun jalostusmateriaalia.', NULL, FALSE, FALSE),
(1, '2', 2, 'Koirien hyvinvoinnin on oltava koiranäyttelyissä aina etusijalla.', NULL, FALSE, FALSE),
(1, '3', 1, 'Näyttelyyn saavat osallistua FCI:n tunnustaman maan kenneljärjestössä rekisteröidyt FCI:n ja Pohjoismaisen Kennelunionin PKU:n hyväksymien rotujen koirat, jotka on tunnistusmerkitty Kennelliiton hyväksymällä tavalla ja täyttävät voimassa olevat Kennelliiton hyväksymät terveysmääräykset.  Kansainvälisissä näyttelyissä rodut, joita FCI ei ole hyväksynyt, sijoitetaan näyttelyluettelossa omaan osioonsa ja ne eivät osallistu ryhmäkilpailuihin.', NULL, FALSE, FALSE),
(1, '3', 2, 'Arvostelun aikana ei koiralla saa olla kuonokoppaa tai muuta vastaavaa hallintavälinettä.', NULL, FALSE, FALSE),
(1, '3', 3, 'Näyttelyyn ei saa osallistua', NULL, FALSE, FALSE),
(1, '3', 4, 'koira, jota ei ole rokotettu Kennelliiton rokotusmääräysten mukaan', NULL, TRUE, TRUE),
(1, '3', 5, 'sairas koira', NULL, TRUE, TRUE),
(1, '3', 6, 'kantava narttu 30 vuorokautta ennen laskettua aikaa (laskettu aika = 63 vrk ensimmäisestä astutuksesta) ja synnyttänyt narttu alle 75 vrk synnytyksen jälkeen', NULL, TRUE, TRUE),
(1, '3', 7, 'Suomen lain vastaisesti typistetyt koirat (erillinen luettelo roduista, joilla esiintyy ns. luonnontöpöhäntäisyyttä)', NULL, TRUE, TRUE),
(1, '3', 8, 'vaarallisen vihainen koira ', NULL, TRUE, TRUE),
(1, '3', 9, 'koira, joka on saanut näyttelyssä kolme kertaa laatumaininnan \”hylätty\” käyttäytymisen takia', NULL, TRUE, TRUE),
(1, '3', 10,'koira, jolle on tehty jokin toimenpide rotumääritelmän mukaan tai muuten viaksi katsottavan ominaisuuden korjaamiseksi', NULL, TRUE, TRUE),
(1, '3', 11,'koira, jonka karvapeite on värjätty tai joka on trimmattu rotumääritelmän vastaisesti, pyrkimyksenä salata esim. pitkäkarvaisuutta tai todellista karvanlaatua', NULL, TRUE, TRUE),
(1, '3', 12,'koiran karvapeitteen, kirsun ja ihon käsitteleminen sellaisilla aineilla, jotka vaikuttavat väriin, muotoon ja rakenteeseen on kielletty.', NULL, TRUE, TRUE),
(1, '3', 13,'yleisen antidoping-säännön vastainen koira (liite 1)', NULL, TRUE, TRUE),
(1, '3', 14,'Sääntöjen vastaisen menettelyn tutkimiseksi on näyttelytoimikunnan valtuuttamalla henkilöllä oikeus ottaa koirista tarvittavia näytteitä näyttelyn aikana tai viiden vuorokauden kuluessa näyttelyn päättymisestä.', NULL, FALSE, FALSE),
(1, '3', 15,'Näyttelyyn osallistumisoikeutta ei ole', NULL, FALSE, FALSE),
(1, '3', 16,'koiralla, jonka omistajalla tai yhdelläkin omistajista on Kennelliiton kurinpitolautakunnan lisäseuraamuksena määräämä kielto tai Kennelliiton hallituksen määräämä tilapäinen kielto osallistua näyttelyihin näytteilleasettajana tai esittäjänä', NULL, TRUE, TRUE),
(1, '3', 17,'kasvattajaryhmällä, jonka kasvattajalla tai yhdelläkin kasvattajisa on Kennelliiton kurinpitolautakunnan lisäseuraamuksena määräämä kielto tai Kennelliiton hallituksen määräämä tilapäinen kielto osallistua näyttelyihin näytteilleasettajana tai esittäjänä', NULL, TRUE, TRUE),
(1, '3.1', 1, 'Näyttelyssä noudatetaan kulloinkin voimassa olevaa Kennelliiton yleistä jääviyssääntöä.', NULL, FALSE, FALSE),
(1, '3.2', 1, 'Näyttelyn eläinlääkäri voi tarkastaa koiria ja todetessaan koiran sairaaksi, hänellä on oikeus poistaa se näyttelystä. Eläinlääkäri voi myös ottaa koirista näytteitä näyttelyn aikana tai viiden vuorokauden kuluessa näyttelyn päättymisestä.', NULL, FALSE, FALSE),
(1, '4', 1, 'Ilmoittautuminen on tehtävä joko postitse tai sähköisesti Kennelliiton hyväksymällä lomakkeella, joka on maksuineen toimitettava näyttelytoimikunnalle ennen ilmoittautumisajan päättymistä. Sekä maksupäivän että kirjeen postileiman päiväyksen on oltava viimeistään ilmoittautumisajan päättymispäivä.', NULL, FALSE, FALSE),
(1, '4', 2, 'Koira on ilmoitettava näyttelyyn sillä nimellä ja sen rotuisena, jolla se on rekisteröity. Se on ilmoitettava laatuarvosteluluokkaan, johon se on oikeutettu osallistumaan.', NULL, FALSE, FALSE),
(1, '4', 3, 'Ilmoittautumisajan päättymisen jälkeen koiraa ei voida siirtää toiseen luokkaan (ellei kysymyksessä ole järjestäjästä johtuva virhe).', NULL, FALSE, FALSE),
(1, '4', 4, 'Jos koirasta on ilmoitettaessa annettu vääriä tietoja, koira voidaan sulkea näyttelystä ja mitätöidä sille jo mahdollisesti annetut tulokset.', NULL, FALSE, FALSE),
(1, '5', 1, 'Ilmoittautumismaksu palautetaan näytteilleasettajan niin halutessa, jos', NULL, FALSE, FALSE),
(1, '5', 2, 'näyttely peruutetaan', NULL, TRUE, TRUE),
(1, '5', 3, 'ilmoittautuminen peruutetaan tuomarimuutoksen vuoksi, ellei näyttelytoimikunta ole etukäteen ennen ensimmäisen ilmoittautumisajan päättymistä ilmoittanut rodulle varatuomaria näyttelyn virallisessa tiedotteessa (Koiramme-Våra hundar)', NULL, TRUE, TRUE),
(1, '5', 4, 'näyttelyilmoittautuminen on myöhästynyt', NULL, TRUE, TRUE),
(1, '5', 5, 'näyttelyyn ilmoitetun koiran kasvattaja kutsutaan kyseisen rodun tuomariksi ilmoittautumisajan päätyttyä ', NULL, TRUE, TRUE),
(1, '5', 6, 'Ilmoittautumismaksua ei palauteta, jos', NULL, FALSE, FALSE),
(1, '5', 7, 'näyttelyyn ilmoitettua koiraa ei ole rokotettu tai tunnistusmerkitty Kennelliiton määräysten mukaisesti', NULL, TRUE, TRUE),
(1, '5', 8, 'näyttelyyn ilmoitettu koira tai sen omistaja sairastuu', NULL, TRUE, TRUE),
(1, '5', 9, 'näyttely peruutetaan force majeure -syystä (yleisötapahtumien kieltäminen viranomaisten toimesta, liikennelakko, koirien terveystilanne jne.)', NULL, TRUE, TRUE),
(1, '5', 10,'Näyttelytoimikunnalla on oikeus periä ilmoittautumismaksun palauttamisesta aiheutuvat pankki- ja käsittelykulut. ', NULL, FALSE, FALSE),
(1, '6', 1, 'Näytteilleasettajan tulee huolehtia koiransa hyvinvoinnista ja hyvästä kohtelusta.', NULL, FALSE, FALSE),
(1, '6', 2, 'Näytteilleasettaja vastaa esittämiensä/omistamiensa koirien näyttelyssä mahdollisesti aiheuttamista vahingoista.', NULL, FALSE, FALSE),
(1, '6', 3, 'Näytteilleasettaja ei saa puhutella arvostelevaa tuomaria näyttelypaikalla ennen arvostelua eikä arvostelun aikana ilman pakottavaa syytä.', NULL, FALSE, FALSE),
(1, '6', 4, 'Näytteilleasettaja ei saa häiritä eikä moittia tuomaria tai muuten käyttäytyä näyttelypaikalla sopimattomasti tai hyvän tavan vastaisesti.', NULL, FALSE, FALSE),
(1, '7', 1, 'Näyttelynjärjestäjän pitää ottaa ryhmätapaturmavakuutus tuomareille ja kehätoimitsijoille sekä vastuuvakuutus, joka kattaa sen osan korvausvastuusta, joka näyttelyiden järjestämisestä voi syntyä yleisöä, toimihenkilöä tai ulkopuolista kohdanneesta henkilö- tai esinevahingosta. ', NULL, FALSE, FALSE),
(1, '8', 1, 'Arvostelevan tuomarin on oltava Suomen Kennelliiton hyväksymä ulkomuototuomari.', NULL, FALSE, FALSE),
(1, '9', 1, 'Ulkomuototuomari antaa jokaisesta arvostelemastaan koirasta kirjallisen lausunnon Kennelliiton lomakkeella. Lomakkeen jäljennös annetaan näytteilleasettajalle.', NULL, FALSE, FALSE),
(1, '9', 2, 'Tuomari voi niin harkitessaan hyväksyä vain Kennelliiton vahvistaman eläinlääkärintodistuksen ja huomioida sen arvostelussaan, jos koiralla on näyttelyarvosteluun vaikuttava vamma (esim. nikamavika hännässä tai hammaspuutos). Esitetystä todistuksesta on tehtävä merkintä arvostelulomakkeeseen.', NULL, FALSE, FALSE),
(1, '9', 3, 'Koiraa ei saa häiritä sitä arvosteltaessa eikä pyrkiä huonontamaan sen kilpailumahdollisuuksia.', NULL, FALSE, FALSE),
(1, '9', 4, 'Koiran esiintymistä ei saa yrittää parantaa kehän sisä- tai ulkopuolella arvostelua häiritsevästi. Ulkomuototuomarin tai kehätoimitsijan tulee puuttua kehän sisä- tai ulkopuolella tapahtuvaan arvostelua häiritsevään toimintaan. ', NULL, FALSE, FALSE),
(1, '9', 5, 'Arvostelusta myöhästynyt koira voi saada ainoastaan laatuarvostelun.', NULL, FALSE, FALSE),
(1, '9', 6, 'Kun koira on tuotu kehään mittausta ja/tai laatuarvostelua varten, se on esitettävä kaikissa niissä kilpailuluokissa, joihin sen saamat palkinnot oikeuttavat sen osallistumaan ellei näyttelytoimikunta ole antanut koiralle lupaa poistua ennen näyttelyn päättymistä.', NULL, FALSE, FALSE),
(1, '10', 1, 'Koirat arvostellaan luokittain näyttelysäännön mukaisessa järjestyksessä. Koirista annetaan kirjallinen laatuarvostelu.', NULL, FALSE, FALSE),
(1, '10.1', 1, 'Laatuarvostelussa annetaan niin monta eri laatumainintaa, kuin koirien laatu edellyttää.', NULL, FALSE, FALSE),
(1, '10.1', 2, 'Laatumaininnat:', NULL, FALSE, FALSE),
(1, '10.1', 3, 'Tuomarin antaman laatuarvostelun tulee vastata seuraavia määritelmiä:', NULL, FALSE, FALSE),
(1, '10.1', 4, 'ERINOMAINEN voidaan antaa koiralle, joka on hyvin lähellä rotumääritelmän ihannetta, joka esitetään erinomaisessa kunnossa, jolla tasapainoinen luonne, joka on korkealuokkainen ja joka on olemukseltaan erinomainen. Sen ulkomuodolliset ansiot ovat suuret ja virheet vähäiset ja sen tulee omata sukupuolelleen tyypilliset piirteet.', NULL, FALSE, FALSE),
(1, '10.1', 5, 'ERITTÄIN HYVÄ voidaan antaa koiralle, joka omaa rodulle tyypilliset piirteet, jolla on tasapainoinen rakenne, ja joka on hyvässä kunnossa. Muutama vähäinen virhe voidaan sallia, mutta ei rakenteellisia virheitä. Tämä laatumaininta voidaan antaa vain tasokkaalle koiralle.', NULL, FALSE, FALSE),
(1, '10.1', 6, 'HYVÄ annetaan koiralle, joka on rodulleen tyypillinen, mutta sillä on selkeitä virheitä.', NULL, FALSE, FALSE),
(1, '10.1', 7, 'TYYDYTTÄVÄ tulee antaa koiralle, joka vastaa rotuaan ilman yleisesti hyväksyttyjä rodun piirteitä, tai jonka fyysisessä kunnossa on toivomisen varaa.', NULL, FALSE, FALSE),
(1, '10.1', 8, 'HYLÄTTY tulee antaa koiralle, joka ei rakenteeltaan vastaa rotumääritelmää, jonka käytös ei ole rotumääritelmän mukainen tai se on selvästi vihainen, jolla on sääntöjen vastainen kivespuutos tai kivesvika, hammaspuutoksia tai poikkeavuutta purennassa tai leuoissa, jonka väritys tai karvapeite on puutteellinen tai joka osoittaa selvästi merkkejä albinismista. ', NULL, FALSE, FALSE),
(1, '10.1', 9, 'Tämä laatumaininta voidaan antaa myös koiralle, joka ei vaikuta terveeltä. Sen lisäksi se voidaan antaa koiralle, jolla on rotumääritelmän vastainen hylkäävä virhe.', NULL, FALSE, FALSE),
(1, '10.1', 10,'Koirat, joille ei voida antaa mitään edellä mainituista laatumaininnoista poistetaan kehästä maininnalla:', NULL, FALSE, FALSE),
(1, '10.1', 11,'EI VOIDA ARVOSTELLA: Tämä maininta annetaan koiralle, joka ei liiku, hyppii jatkuvasti esittäjänsä ympärillä tai pyrkii ulos kehästä, jonka liikkeitä on mahdoton arvostella tai jos koira jatkuvasti välttelee tuomarin käsittelyä ja tekee mahdottomaksi tarkastaa purennan ja hampaat, rakenteen, hännän tai kivekset, tai jos on havaittavissa jälkiä toimenpiteistä tai käsittelystä, jotka näyttävät vilpin yritykseltä tai tuomarilla on syytä epäillä, että koiralla olevaa vikaa on korjailtu (esim. silmäluomia, korvia tai häntää). Syy, miksi koiraa ei voida arvostella, on kirjattava arvosteluun.', NULL, FALSE, FALSE),
(1, '10.2', 1, 'Kilpailuarvostelussa tuomari sijoittaa luokittain erinomainen ja erittäin hyvä laatumaininnalla palkitut neljä (4) parasta koiraa paremmuusjärjestykseen. Nämä saavat merkinnän sijoituksesta arvosteluunsa.', NULL, FALSE, FALSE),
(1, '10.2', 2, 'Tuomari voi harkintansa mukaan antaa sekä kilpailuarvostelussa sijoittuneille että muille luokassa kilpailleille, erinomaisella palkituille koirille SERTIFIKAATIN ARVOISEN (SA), joka oikeuttaa koiran osallistumaan paras uros- ja paras narttu -luokkaan.', NULL, FALSE, FALSE),
(1, '11', 1, 'Koira voi kasvattaja – ja jalostusluokkaa lukuun ottamatta kilpailla vain yhdessä laatuarvosteluluokassa, joka ilmoittajalla on mahdollisuus valita sääntöjen mukaan.', NULL, FALSE, FALSE),
(1, '11', 2, 'Urokset ja nartut arvostellaan erikseen lukuun ottamatta rotunsa paras- kasvattaja- ja jalostusluokkia, ryhmäkilpailuja ja Best in Show -kilpailua.', NULL, FALSE, FALSE),
(1, '11', 3, 'Koira voidaan ilmoittaa vain yhteen seuraavista luokista (a-h) ', NULL, FALSE, FALSE),
(1, '11.a', 1, 'Kilpailuarvostelu koirille, jotka viimeistään näyttelypäivänä täyttävät viisi kuukautta, mutta eivät ole täyttäneet seitsemää kuukautta. Tuomari voi antaa kunniapalkinnon pennuille, jotka hän katsoo sen arvoisiksi. Pikkupentuluokka voidaan järjestää vain rotujärjestön / rotua harrastavan yhdistyksen erikoisnäyttelyissä.', NULL, FALSE, FALSE),
(1, '11.b', 1, 'Kilpailuarvostelu koirille, jotka viimeistään näyttelypäivänä täyttävät seitsemän kuukautta, mutta eivät ole täyttäneet yhdeksää kuukautta. Tuomari voi antaa kunniapalkinnon pennuille, jotka hän katsoo sen arvoisiksi.', NULL, FALSE, FALSE),
(1, '11.b', 2, 'Paras kunniapalkinnon saanut uros- ja narttupentu osallistuu rotunsa paras pentu -kilpailuun.', NULL, FALSE, FALSE),
(1, '11.b', 3, 'Pentuluokat ovat epävirallisia ja järjestetään vain näyttelytoimikunnan niin halutessa.', NULL, FALSE, FALSE),
(1, '11.b', 4, 'Best in Show pentu -kilpailu voidaan järjestää vain erikoisnäyttelyissä.', NULL, FALSE, FALSE),
(1, '11.c', 1, 'Laatuarvostelu koirille, jotka viimeistään näyttelypäivänä täyttävät yhdeksän (9) kuukautta, mutta eivät ole täyttäneet kahdeksaatoista (18) kuukautta.', NULL, FALSE, FALSE),
(1, '11.d', 1, 'Laatuarvostelu koirille, jotka viimeistään näyttelypäivänä täyttävät viisitoista (15) kuukautta, mutta eivät ole täyttäneet kahtakymmentäneljää (24) kuukautta.', NULL, FALSE, FALSE),
(1, '11.e', 1, 'Laatuarvostelu koirille, jotka viimeistään näyttelypäivänä täyttävät viisitoista (15) kuukautta. Luokassa ei ole yläikärajaa.', NULL, FALSE, FALSE),
(1, '11.f', 1, 'Laatuarvostelu koirille, jotka viimeistään näyttelypäivänä täyttävät viisitoista (15) kuukautta.', NULL, FALSE, FALSE),
(1, '11.f', 2, 'Kansainvälisissä näyttelyissä käyttöluokkaan voi ilmoittaa vain rodun, jonka FCI määrittelee käyttökoiraroduksi tai jolle FCI on erikseen antanut osallistumisoikeuden. (liite 3, lista roduista).', NULL, FALSE, FALSE),
(1, '11.f', 3, 'Näillä roduilla sekä kansainvälisissä että kansallisissa näyttelyissä osallistumiseen oikeuttava koetulos on vähintään Suomen tai kansainvälisen muotovalion arvoon vaadittava koetulos tai koetulokset.', NULL, FALSE, FALSE),
(1, '11.f', 4, 'Vinttikoirien käyttöluokkaan osallistumisen ehtona on voimassa oleva kilpailukirja. Lisäksi koiran on täytynyt osallistua vähintään kahteen (2) kansainväliseen kilpailuun (CACIL) ja sen on molemmissa kilpailuissa oltava sijoittunut parhaaseen puolikkaaseen osallistujamäärästä. Maastojuoksukilpailuissa koiran on täytynyt saavuttaa vähintään 2/3 enimmäispistemäärästä. Kilpailutulosten välillä tulee olla vähintään yksi vuosi ja yksi päivä. Ilmoitettaessa vinttikoira käyttöluokkaan on kopio koiran kilpailukirjasta oheistettava näyttelytoimikunnalle.', NULL, FALSE, FALSE),
(1, '11.f', 5, 'Kansallisissa näyttelyissä ne rodut, jotka voivat saavuttaa Suomessa käyttövalion arvon, mutta eivät kuulu FCI:n määrittelemiin käyttökoirarotuihin, voivat osallistua käyttöluokkaan saavutettuaan käyttövalion arvon.', NULL, FALSE, FALSE),
(1, '11.f', 6, 'Poikkeuksena ovat alaskanmalamuutti, grönlanninkoira, samojedinkoira ja siperianhusky, joilta vaaditaan hyväksytty tulos rodunomaisesta kokeesta.', NULL, FALSE, FALSE),
(1, '11.f', 7, 'Luonnetestitulos ei oikeuta osallistumaan käyttöluokkaan.', NULL, FALSE, FALSE),
(1, '11.g', 1, 'Laatuarvostelu koirille, jotka viimeistään näyttelypäivänä täyttävät viisitoista (15) kuukautta ja ovat jonkin FCI:n tunnustaman kenneljärjestön tai kansainvälisiä muotovalioita. Suomen muotovalio on ilmoitettava aina valioluokkaan, ellei koiralla ole oikeutta osallistua käyttö- tai veteraaniluokkaan.', NULL, FALSE, FALSE),
(1, '11.h', 1, 'Laatuarvostelu koirille, jotka viimeistään näyttelypäivänä täyttävät kahdeksan (8) vuotta.', NULL, FALSE, FALSE),
(1, '11.h', 2, 'Rotunsa paras veteraani, joka on palkittu laatumaininnalla erinomainen, saa jatkaa edelleen kilpailemista Best in Show veteraanin arvosta.', NULL, FALSE, FALSE),
(1, '11.i', 1, 'Tähän luokkaan ovat oikeutettuja osallistumaan koirat, jotka on (sijoittuneet juniori-, nuorten-, avoin-, valio-, käyttö- tai veteraaniluokassa neljän parhaan joukkoon laatumaininnalla erinomainen ja) palkittu sertifikaatin arvoisella (SA). ', NULL, FALSE, FALSE),
(1, '11.i', 2, 'Tuomari voi antaa sertifikaatin parhaalle siihen oikeutetulle sertifikaatin arvoisella (SA) palkitulle koiralle, jolla ei ole Suomen muotovalion arvoon oikeuttavia näyttelytuloksia. Varasertifikaatin voi saada toiseksi paras sertifikaatin arvoisella (SA) palkittu koira, jolla ei ole Suomen muotovalion arvoon oikeuttavia näyttelytuloksia.', NULL, FALSE, FALSE),
(1, '11.i', 3, 'Tuomari voi niin harkitessaan esittää CACIBia parhaaksi katsomalleen siihen oikeutetulle koiralle ja varaCACIBia toiseksi parhaaksi katsomalleen siihen oikeutetulle koiralle, jotka ovat kilpailleet nuortenluokassa, avoimessa luokassa, käyttöluokassa tai valioluokassa. ', NULL, FALSE, FALSE),
(1, '11.j', 1, 'Rodun parhaan valintaan osallistuvat paras uros ja paras narttu.', NULL, FALSE, FALSE),
(1, '11.j', 2, 'Rotunsa paras koira osallistuu ryhmäkilpailuun.', NULL, FALSE, FALSE),
(1, '11.k', 1, 'Kasvattajaluokka on laatuarvostelu, jossa kilpailee neljän samanrotuisen koiran muodostama ryhmä. Koirien on oltava saman kasvattajan kasvattamia tai samalle FCI:n vahvistamalle kennelnimelle rekisteröityjä. Lisäksi koirien on oltava palkittu laatumaininnalla erinomainen tai erittäin hyvä tässä näyttelyssä.', NULL, FALSE, FALSE),
(1, '11.k', 2, 'Kasvattaja saa kilpailla yhdessä näyttelyssä vain yhdellä ryhmällä rotua kohti.', NULL, FALSE, FALSE),
(1, '11.k', 3, 'Jos tuomari katsoo ryhmän olevan riittävän tasalaatuinen ja korkeatasoinen, hän voi antaa kunniapalkinnon.', NULL, FALSE, FALSE),
(1, '11.k', 4, 'Kasvattajaluokan kilpailuarvostelu (KAK). Tuomari sijoittaa neljä (4) kasvattajaryhmää paremmuusjärjestykseen. Mikäli rodun paras ryhmä on saanut kunniapalkinnon, se osallistuu Best in Show -kasvattajaryhmän valintaan.', NULL, FALSE, FALSE),
(1, '11.l', 1, 'Rodun paras kunniapalkinnolla palkittu kasvattajaryhmä osallistuu näyttelyn parhaan kasvattajaryhmän valintaan. Tuomari sijoittaa neljä (4) parasta ryhmää paremmuusjärjestykseen.', NULL, FALSE, FALSE),
(1, '11.m', 1, 'Jälkeläisluokka on laatuarvostelu, jossa uros tai narttu kilpailee neljän samanrotuisen jälkeläisensä muodostamalla ryhmällä. Jälkeläisten tulee olla palkittu laatumaininnalla erinomainen tai erittäin hyvä tässä näyttelyssä. Urosta tai narttua ei tarvitse ilmoittaa muihin luokkiin, mutta se tulee esittää jälkeläisryhmänsä kanssa.', NULL, FALSE, FALSE),
(1, '11.m', 2, 'Jälkeläisluokka voidaan järjestää vain rotujärjestön/rotua harrastavan yhdistyksen erikoisnäyttelyissä.', NULL, FALSE, FALSE),
(1, '11.m', 3, 'Jos tuomari katsoo ryhmän olevan riittävän tasalaatuinen ja korkeatasoinen, hän voi antaa kunniapalkinnon.', NULL, FALSE, FALSE),
(1, '11.m', 4, 'Jälkeläisluokan kilpailuarvostelu (JÄK). Tuomari sijoittaa neljä (4) jälkeläisryhmää paremmuusjärjestykseen. Mikäli rodun paras ryhmä on saanut kunniapalkinnon, se osallistuu Best in Show -jälkeläisryhmän valintaan.', NULL, FALSE, FALSE),
(1, '11.n', 1, 'Rodun paras kunniapalkinnolla palkittu jälkeläisryhmä osallistuu näyttelyn parhaan jälkeläisryhmän valintaan. Tuomari sijoittaa neljä (4) parasta ryhmää paremmuusjärjestykseen. BIS-JÄL voidaan järjestää vain rotujärjestön/rotua harrastavan yhdistyksen erikoisnäyttelyissä.', NULL, FALSE, FALSE),
(1, '11.o', 1, 'Kilpailuun osallistuvat rotunsa parhaat veteraaniluokissa kilpailleet koirat. Tuomari sijoittaa neljä (4) parasta koiraa paremmuusjärjestykseen.', NULL, FALSE, FALSE),
(1, '11.p', 1, 'Kilpailuun osallistuvat rotunsa parhaat koirat roturyhmittäin. Tuomari sijoittaa neljä (4) parasta koiraa paremmuusjärjestykseen.', NULL, FALSE, FALSE),
(1, '11.q', 1, 'Best in Show valitaan ryhmien voittajista. Tuomari sijoittaa neljä (4) parasta koiraa paremmuusjärjestykseen.', NULL, FALSE, FALSE),
(1, '12', 1, 'Laatuarvostelun tulos osoitetaan seuraavin värein:', NULL, FALSE, FALSE),
(1, '12', 2, 'erinomainen		punainen', NULL, TRUE, TRUE),
(1, '12', 3, 'erittäin hyvä		sininen', NULL, TRUE, TRUE),
(1, '12', 4, 'hyvä			keltainen', NULL, TRUE, TRUE),
(1, '12', 5, 'tyydyttävä		vihreä', NULL, TRUE, TRUE),
(1, '12', 6, 'hylkäävä			harmaa', NULL, TRUE, TRUE),
(1, '12', 7, 'ei voida arvostella	ruskea', NULL, TRUE, TRUE),
(1, '12', 8, 'sertifikaatin arvoinen	vaaleanpunainen', NULL, TRUE, TRUE),
(1, '12', 9, 'Kilpailuarvostelun sijoitukset osoitetaan seuraavin värein:', NULL, FALSE, FALSE),
(1, '12', 10,'1. punainen', NULL, TRUE, TRUE),
(1, '12', 11,'2. sininen', NULL, TRUE, TRUE),
(1, '12', 12,'3. keltainen', NULL, TRUE, TRUE),
(1, '12', 13,'4. vihreä', NULL, TRUE, TRUE),
(1, '12', 14,'Näyttelyssä jaettavat palkintoruusukkeet ja nauhat:', NULL, FALSE, FALSE),
(1, '12', 15,'sertifikaatti	sinivalkoinen', NULL, TRUE, TRUE),
(1, '12', 16,'varasertifikaatti	vaaleansininen', NULL, TRUE, TRUE),
(1, '12', 17,'CACIB		valkoinen', NULL, TRUE, TRUE),
(1, '12', 18,'vara-CACIB	oranssi', NULL, TRUE, TRUE),
(1, '12', 19,'ROP		punakeltainen', NULL, TRUE, TRUE),
(1, '12', 20,'VSP		valkovihreä ', NULL, TRUE, TRUE),
(1, '12', 21,'kunniapalkinto	lila', NULL, TRUE, TRUE),
(1, '12', 22,'Suomen muotovalio punavihreä', NULL, TRUE, TRUE),
(1, '13', 1, 'Tuomarin päätös on lopullinen, eikä siitä voi valittaa. Tuomari ei voi muuttaa koirasta antamaansa arvostelua, ellei ole sattunut järjestely- tai muuta siihen verrattavaa virhettä (esim. koira on arvosteltu luokassa, johon sillä ei ole ollut oikeutta osallistua). Muutos on suoritettava yhdessä näyttelytoimikunnan jäsenen kanssa.', NULL, FALSE, FALSE),
(1, '13', 2, 'Mikäli kyseessä on merkintävirhe, joka voidaan tulosten perusteella oikaista, voidaan se tehdä myös Kennelliitossa tulosten tarkastuksen yhteydessä.', NULL, FALSE, FALSE),
(1, '13', 3, 'Tuomarin arvostelusta voi valittaa ainoastaan, mikäli tuomari on toiminut näiden sääntöjen tai hyvän tavan vastaisesti.', NULL, FALSE, FALSE),
(1, '14', 1, 'Koiranäyttelysääntöjä täydentävät Kennelliiton hallituksen antamat koiranäyttelyiden järjestämisohjeet, ulkomuototuomareiden toimintaohjeet, Kennelliiton antamat muut säännöt ja ohjeet sekä sen käyttöönottamat FCI:n ohjeet.', NULL, FALSE, FALSE),
(1, '14', 2, 'Kennelliiton hallitus voi pakottavista syistä rajoittaa näyttelyyn osallistumista tai antaa muita näyttelyn toimeenpanoa koskevia erikoismääräyksiä.', NULL, FALSE, FALSE),
(1, '15', 1, 'Valitukset tehdään Kennelliiton vahvistaman muutoksenhakumenettelyn mukaisesti. (liite 4)', NULL, FALSE, FALSE),
(1, '16', 1, 'Nämä säännöt ovat voimassa 1.1.2017 - 31.12.2021.', NULL, FALSE, FALSE),
(2, 'A.1', 1, 'Koiran hyvinvoinnin huomioonottaminen on ensiarvoisen tärkeää kaikissa koiranäyttelyissä.', NULL, FALSE, FALSE),
(2, 'A.2', 1, 'Koira voi osallistua näyttelyyn, jos se on rekisteröity johonkin Fédération Cynologique Internationalen (jäljempänä FCI) tunnustamaan koirarekisteriin. Rodun tulee olla FCI:n tai Pohjoismaisen Kennelunionin PKU:n hyväksymä.', NULL, FALSE, FALSE),
(2, 'A.2', 2, 'Näyttelyyn osallistuvan koiran tiedot on oltava näyttelyluettelossa. Näyttelyluettelosta puuttuva koira voidaan arvostella vain jos virhe on ollut näyttelytoimikunnan aiheuttama. Kaikkien näyttelyyn osallistuvien koirien on oltava rokotettu Suomen Kennelliiton – Finska Kennelklubben ry:n (jäljempänä Kennelliitto) voimassaolevien rokotusmääräysten mukaisesti ja koirien on muutoinkin täytettävä em. ohjeessa tartuntatautien leviämisen varalta annetut määräykset.', NULL, FALSE, FALSE),
(2, 'A.2', 3, 'Kaikkien näyttelyyn osallistuvien koirien on täytettävä Kennelliiton voimassaolevat tunnistusmerkintämääräykset. Tunnistusmerkintöjen tarkastaminen on näyttelynjärjestäjän vastuulla ja tunnistusmerkinnät tarkastetaan pistokokein.', NULL, FALSE, FALSE),
(2, 'A.2', 4, 'Rokotusmääräysten noudattamisen valvonta on näyttelyn järjestäjän vastuulla.', NULL, FALSE, FALSE),
(2, 'A.2', 5, 'Rokotustodistukset voidaan näyttelyn järjestäjän harkinnan mukaan tarkastaa pistokokein, mikäli koiramäärä on yli 2000.', NULL, FALSE, FALSE),
(2, 'A.2', 6, 'Näyttelypaikalle ei ilman näyttelytoimikunnan lupaa saa tuoda koiria, joita ei ole ilmoitettu näyttelyyn. Jos ulkopuolisten koirien tulo näyttelyalueelle sallitaan, koirat on ehdottomasti tarkastettava samalla tavoin kuin näyttelyyn ilmoitetut koirat ja niiden on täytettävä edellä mainitut Kennelliiton voimassaolevat rokotus- ja terveys- sekä tunnistusmerkintämääräykset. Nartun astuttaminen näyttelyalueella on kielletty. Näyttelyalueelle ei saa tuoda narttua, jonka oletettuun synnytysaikaan on vähemmän kuin 30 vuorokautta eikä narttua, jonka synnytyksestä on kulunut alle 75 vuorokautta.', NULL, FALSE, FALSE),
(2, 'A.2', 7, 'Koiranpentujen tuominen näyttelyalueelle myyntitarkoituksessa sekä pentujen kaupittelu ja luovutus näyttelyssä ja sen välittömässä läheisyydessä on ehdottomasti kielletty.', NULL, FALSE, FALSE),
(2, 'A.2', 8, 'Henkilö, jolla on eläintenpitokielto, ei voi osallistua näyttelyyn näytteilleasettajana tai koiran esittäjänä.', NULL, FALSE, FALSE),
(2, 'A.3.1', 1, 'Kansainvälisiin ja kaikkien rotujen näyttelyihin ilmoittautumisaika päättyy viimeistään kuukautta, ryhmä- ja erikoisnäyttelyihin viimeistään kahta viikkoa ennen näyttelyajankohtaa. Ilmoittautumisaika voi olla lyhempi, mikäli näyttelyjärjestäjällä on siihen valmius.', NULL, FALSE, FALSE),
(2, 'A.3.1', 2, 'Virallisessa Koiramme-lehden Kennelliiton tiedotuksia-osiossa (jäljempänä Koirammelehdessä) ja näyttelyn tiedotteissa annettua ilmoittautumisaikaa ei saa kuitenkaan muuttaa, lyhentää tai pidentää.', NULL, FALSE, FALSE),
(2, 'A.3.1', 3, 'Ilmoittautumisen täytyy olla todistettavasti maksettu (kuitti) viimeisenä ilmoittautumispäivänä ja lähetetty (postileima) viimeistään viimeistä ilmoittautumispäivää seuraavana ensimmäisenä arkipäivänä.', NULL, FALSE, FALSE),
(2, 'A.3.1', 4, 'Mikäli ilmoittautuminen ei ole saapunut näyttelyn järjestäjälle viikon sisällä viimeisestä ilmoittautumispäivästä, voi näyttelyn järjestäjä katsoa ilmoittautumisen myöhästyneeksi.', NULL, FALSE, FALSE),
(2, 'A.3.1', 5, 'Näyttelyn järjestäjä ei vastaa postissa kadonneista tai viivästyneistä ilmoittautumisista.', NULL, FALSE, FALSE),
(2, 'A.3.1', 6, 'Ilmoittautuminen on mahdollista myös ainoastaan sähköisesti, mikäli näyttelyn järjestäjä niin haluaa. Sähköisen ilmoittautumisen ehdoton edellytys on, että ilmoittautumismaksu suoritetaan ilmoittautumisen yhteydessä ja että ilmoittautuja voidaan luotettavasti yksilöidä.', NULL, FALSE, FALSE),
(2, 'A.3.1', 7, 'Pelkkä maksukuitti ei ole ilmoittautuminen. Myöhästyneet ilmoittautumiset palautetaan. Käyttö- ja valioluokkaan ilmoitettaessa Kennelliitossa rekisteröidyiltä koirilta ei vaadita todistusta näihin luokkiin vaadittavista tuloksista. Muiden maiden rekisterissä olevilla koirilla on oltava valionarvotodistus ja/tai käyttökoetodistus ilmoittautumisen liitteenä.', NULL, FALSE, FALSE),
(2, 'A.3.1', 8, 'Käyttökoetodistuksen on oltava myönnetty siinä FCI:n jäsenmaassa, jossa koiran haltijalla ja/tai omistajalla on vakituinen asuinpaikka.', NULL, FALSE, FALSE),
(2, 'A.3.1', 9, 'Koiran ilmoittautumisasiakirjoihin on tarvittaessa liitettävä eläinlääkärin todistus hännän amputoinnista. Osittain tai kokonaan suomalaisomistuksessa olevalta koiralta vaaditaan, että todistus on Kennelliiton eläinlääkintälomakkeella.', NULL, FALSE, FALSE),
(2, 'A 3.2', 1, 'Kansainvälisissä, kaikkien rotujen ja ryhmänäyttelyissä ei saa olla luokkia alle 7 kk:n ikäisille koirille. Rotujärjestöjen ja rotua harrastavien yhdistysten itse järjestämissä erikoisnäyttelyissä saa olla ns. pikkupentu-luokka 5 - alle 7 kk ikäisille koirille.', NULL, FALSE, FALSE),
(2, 'A 3.2', 2, 'Jos näyttelyssä järjestetään muita kuin säännöissä ja ohjeissa mainittuja luokkia tai kilpailuja, niistä on oltava maininta näyttelyn tiedotteissa.', NULL, FALSE, FALSE),
(2, 'A 3.2', 3, 'Koiran voi ilmoittaa näyttelyyn vain siihen luokkaan, johon sillä on ilmoittautumishetkellä koe- tai näyttelytulostensa perusteella osallistumisoikeus.', NULL, FALSE, FALSE),
(2, 'A 3.2', 4, 'Ilmoittautumisajan päätyttyä luokkaa voi vaihtaa vain jos ilmoittautumisessa on tapahtunut näyttelysääntöjen vastainen virhe (koira on ilmoitettu luokkaan jossa sillä ei ole ikänsä tai koetulostensa perusteella oikeutta kilpailla).', NULL, FALSE, FALSE),
(2, 'A.3.3', 1, 'Ilmoittautumismaksut määrää näyttelytoimikunta. Kennelliitto määrää junior handler -kilpailujen korkeimman sallitun osallistumismaksun vuosittain. Kasvattaja- ja jälkeläisluokista ei peritä ilmoittautumismaksua.', NULL, FALSE, FALSE),
(2, 'A.3.3', 2, 'Näyttelyn järjestäjä voi halutessaan käyttää ilmoittautumisajan, näyttelyluokan ja/tai näytteilleasettajan näyttelyyn ilmoittamien, hänen omistamiensa koirien lukumäärän mukaan porrastettuja ilmoittautumismaksuja. Käytettäessä ilmoitettujen koirien lukumäärään perustuvia porrastettuja ilmoittautumismaksuja lasketaan ensimmäisiksi koiriksi vain kunkin ilmoittautumisjakson alentamattomat ilmoittautumismaksut. Ilmoittautumismaksut sekä niiden mahdolliset porrastusperusteet on selkeästi ja sitovasti mainittava Koiramme-lehdessä ja näyttelyn tiedotteissa. Näytteilleasettajan pyynnöstä palautettavista ilmoittautumismaksuista (ks. Koiranäyttelysäännöt kohta 5) voidaan vähentää pankkikulut.', NULL, FALSE, FALSE),
(2, 'A.3.3', 3, 'Näyttelytoimikunnan on em. tapauksissa palautettava ilmoittautumismaksu neljän viikon kuluessa siitä, kun näytteilleasettaja on toimittanut pankkiyhteystietonsa toimikunnalle. Näytteilleasettajan tekemiä matkoja näyttelypaikkakunnalle tai muita kuluja ei korvata.', NULL, FALSE, FALSE),
(2, 'A.3.4', 1, 'Ilmoittautumista ei voi peruuttaa sen jälkeen, kun se maksuineen on toimitettu näyttelyn järjestäjälle, vaikka ilmoittautumisaika ei olisi vielä mennyt umpeen. (ks. Ulkomuototuomarimuutokset, kohta A.12.2).', NULL, FALSE, FALSE),
(2, 'A.4', 1, 'Koira ei voi vastaanottaa sertifikaattia, mikäli sillä on Suomen muotovalion arvoon oikeuttavat näyttelytulokset tai siltä puuttuu muotovalion arvosta vain siihen määrätyt lisävaatimukset. Mikäli sertifikaatti on kehässä jaettu koiralle, jolla ei olisi ollut oikeutta vastaanottaa sitä, siirretään sertifikaatti tulostallennuksen yhteydessä varasertifikaatin saaneelle koiralle.', NULL, FALSE, FALSE),
(2, 'A.5', 1, 'Kansainvälisessä näyttelyssä ulkomuototuomari voi esittää CACIBia parhaaksi katsomalleen urokselle ja nartulle, mikäli pitää niitä kansainvälisen muotovalion arvoisina. Toiseksi parhaaksi katsomalleen urokselle ja nartulle ulkomuototuomari voi esittää vara-CACIBia. Suomalaisille roduille CACIB ja vara-CACIB on kuitenkin jaettava parhaille SA:lla palkituille uroksille ja nartuille, jotka ovat oikeutettuja kilpailemaan CACIBista ja vara-CACIBista.', NULL, FALSE, FALSE),
(2, 'A.5', 2, 'Mikäli CACIBin saanut koira on jo kansainvälinen muotovalio tai se ei muutoin täytä FCI:n kulloinkin asettamia edellytyksiä CACIBin saamiselle, FCI vahvistaa tuomarin esittämän CACIBin vara-CACIBin saaneelle koiralle, mikäli se täyttää ko. edellytykset. Näyttelypaikalla ei voi kieltäytyä vastaanottamasta ko. palkintoja, vaikka koira olisikin kansainvälinen muotovalio.', NULL, FALSE, FALSE),
(2, 'A.5', 3, 'FCI määrää kulloinkin rodut ja rotumuunnokset, jotka voivat kilpailla CACIBista (Liite 1). Kennelliitto anoo CACIBit FCI:ltä kolmen kuukauden sisällä näyttelyn päättymisestä.', NULL, FALSE, FALSE),
(2, 'A.6', 1, 'Siirrot rodusta tai rotumuunnoksesta toiseen tapahtuvat liitteen 3 mukaisesti. Tarkastuksen suorittaa rodulle pätevöity ulkomuototuomari ennen kyseisten rotujen arvostelun aloittamista. Mikäli ulkomuototuomari mittauksen tai arvioinnin tuloksena toteaa koiran kuuluvan toiseen rotuun tai rotumuunnokseen, on täytettävä virallinen ”Siirto rodusta toiseen” -lomake. Yksi lomakkeen jäljennös annetaan näytteilleasettajalle ja muut liitetään näyttelyarvostelulomakkeeseen.', NULL, FALSE, FALSE),
(2, 'A.6', 2, 'Koira on arvosteltava heti samassa näyttelyssä siinä rodussa tai rotumuunnoksessa, johon se siirrettiin, eikä se myöhemminkään saa jatkaa kilpailemista aiemmassa rodussaan tai rotumuunnoksessa. Rodusta tai rotumuunnoksesta toiseen tapahtuneen siirron jälkeen kaikki koiran aikaisemmat näyttelytulokset mitätöidään.', NULL, FALSE, FALSE),
(2, 'A.6', 3, 'Kennelliitto tekee muutokset koirarekisteriin ja lähettää uuden rekisteritodistuksen suomalaiselle näytteilleasettajalle. Uudesta rekisteritodistuksesta peritään vain toimituskulut. Ulkomaisen näytteilleasettajan kotimaan kennelliitolle lähetetään tiedot koiran siirrosta rodusta tai rotumuunnoksesta toiseen.', NULL, FALSE, FALSE),
(2, 'A.6', 4, 'Kennelliiton toimisto voi myös tehdä siirron kahden rodulle pätevöidyn kotimaisen ulkomuototuomarin ”Siirto rodusta toiseen” -lomakkeella antaman lausunnon perusteella. Siirto voidaan tehdä vain kerran. Kennelliitto voi kuitenkin omistajan kirjallisen anomuksen perusteella oikaista tehdyn rotumuunnoksesta toiseen siirron rodun rotujärjestön antaman lausunnon perusteella. Anomuksen liitteenä tulee olla myös kahden rodulle pätevöidyn kotimaisen ulkomuototuomarin antama yhteinen lausunto.', NULL, FALSE, FALSE),
(2, 'A.7', 1, 'Ulkomuototuomari tarkastaa arvostelun aikana kaikkien uroskoirien kivekset.', NULL, FALSE, FALSE),
(2, 'A.7', 2, 'Myös pentuluokassa (7 kk - alle 9 kk, erikoisnäyttelyissä myös 5 kk - alle 7 kk) kilpailevalla uroksella on oltava normaalit kivekset.', NULL, FALSE, FALSE),
(2, 'A.7', 3, 'Mikäli arvosteleva tuomari toteaa koiran kivesvikaiseksi, sille annetaan laatumaininta hylätty ja kirjallinen arvostelu, jossa mainitaan hylkäyksen syy. Jos kyse on pentuluokan koirasta, sille annetaan kirjallinen arvostelu, mutta sitä ei sijoiteta.', NULL, FALSE, FALSE),
(2, 'A.8', 1, 'Mikäli arvosteleva ulkomuototuomari epäilee koiran olevan sekarotuinen, lausunto kirjataan arvostelulomakkeeseen. Hän ja toinen ko. rodulle pätevöity ulkomuototuomari vahvistavat lausunnon allekirjoituksellaan.', NULL, FALSE, FALSE),
(2, 'A.8', 2, 'Kennelliiton hallitus voi poistaa ko. koiran koirarekisteristä saatuaan tiedon asiasta sekä hankittuaan tarpeelliseksi katsomansa selvityksen koiran sekarotuisuudesta.', NULL, FALSE, FALSE),
(2, 'A.9', 1, 'Mikäli ulkomuototuomari koiraa arvostellessaan toteaa tai epäilee, että sille on tehty jokin sääntöjen vastainen toimenpide sen ulkomuodon muuttamiseksi, ainoastaan hän voi käynnistää toimenpiteet asian tutkimiseksi.', NULL, FALSE, FALSE),
(2, 'A.9', 2, 'Näyttelysäännön vastaisia käsittelyjä koskevista selvistä epäilyistä on tehtävä ko. ulkomuototuomarin allekirjoituksella varustettu merkintä arvostelulomakkeeseen. Koiralle annetaan EVA, koska sitä ei voida kaikilta osin arvostella.', NULL, FALSE, FALSE),
(2, 'A.9', 3, 'Sääntöjen vastaisen menettelyn tutkimiseksi on näyttelytoimikunnan valtuuttamalla henkilöllä oikeus ottaa koirista tarvittavia näytteitä näyttelyn aikana tai viiden vuorokauden kuluessa näyttelyn päättymisestä.', NULL, FALSE, FALSE),
(2, 'A.9', 4, 'Antidopingsäännön mukaan tavanomaiset turkin hoitoon, pesuun ja trimmaukseen tarvittavat aineet kuitenkin sallitaan. Aineiden käyttämisellä ei saa pyrkiä vaikuttamaan koiran suorituskykyyn, karvan laatuun, väriin tai karvapeitteen muotoon. Niiden käyttäminen ei myöskään saa aiheuttaa haittaa koirien terveydelle ja hyvinvoinnille.', NULL, FALSE, FALSE),
(2, 'A.10.1', 1, 'Koiran saatua kolme kertaa laatumaininnan hylätty sillä perusteella, että koira on selvästi vihainen, Kennelliitto voi asettaa koiran näyttelykieltoon, jonka pituus määrätään tapauskohtaisesti. Koiralle voidaan asettaa näyttelykielto jo yhden vihaisuuden vuoksi saadun laatumaininnan hylätty perusteella, mikäli tapauksen seuraukset ovat olleet vakavat. Näyttelykiellon pituutta määrättäessä otetaan erityisesti huomioon tapausten seuraukset ja niiden vakavuus.', NULL, FALSE, FALSE),
(2, 'A.10.2', 1, 'Koiran hyökättyä tai käytyä kiinni ihmiseen tai toiseen koiraan näyttelyalueella tai sen välittömässä läheisyydessä siten, että koirasta on tehty ilmoitukset kolmesta eri tapauksesta, Kennelliitto voi asettaa sen näyttelykieltoon, jonka pituus määrätään tapauskohtaisesti. Koiralle voidaan asettaa näyttelykielto jo yhden vihaisuuden vuoksi tehdyn ilmoituksen perusteella, mikäli tapauksen seuraukset ovat olleet vakavat. Näyttelykiellon pituutta määrättäessä otetaan erityisesti huomioon tapausten seuraukset ja niiden vakavuus. Näyttelykiellon lisäksi koiran siinä näyttelyssä mahdollisesti saavuttamat tulokset poistetaan.', NULL, FALSE, FALSE),
(2, 'A.10.3', 1, 'Kehässä arvostelevan ulkomuototuomarin on tehtävä ilmoitus vihaisuuden vuoksi saadusta laatumaininnasta hylätty. Ilmoituksen siitä, että koira on näyttelyalueella tai sen välittömässä läheisyydessä hyökännyt tai käynyt kiinni ihmiseen tai toiseen koiraan tai käyttäytynyt muutoin uhkaavasti, tekee ensisijaisesti se henkilö, joka itse taikka jonka koira on joutunut edellä kuvatun käyttäytymisen kohteeksi. Toissijaisesti ilmoituksen voi tehdä näyttelytoimikunnan jäsen, näyttelyohjaaja taikka näyttelyn eläinlääkäri.', NULL, FALSE, FALSE),
(2, 'A.10.4', 1, 'Ilmoitus laaditaan näyttelyn aikana näyttelytoimikunnalle Kennelliiton vahvistamalle lomakkeelle, jonka ilmoituksen tekijä varmentaa allekirjoituksellaan. Ilmoitukseen on pyrittävä saamaan myös sen henkilön lausunto, jonka koiran käyttäytymisestä kyseinen ilmoitus tehdään sekä tapauksen mahdollisten silminnäkijöiden nimet ja yhteystiedot erityisesti sen selvittämiseksi, mistä syystä ilmoituksen tekemiseen johtanut tapahtuma on aiheutunut. Näyttelytoimikunnan velvollisuutena on pitää ilmoituslomakkeita saatavilla näyttelyssä sekä heti näyttelyn päätyttyä toimittaa ilmoitukset Kennelliittoon koiran tietoihin kirjattavaksi. IlmoitusIomakkeesta menee yksi kappale tiedoksi rotujärjestölle. Ilmoitus voidaan tehdä myös koirasta, joka on käyttäytynyt vihaisesti näyttelyalueella tai sen välittömässä läheisyydessä, vaikka sitä ei ole ilmoitettu kyseiseen näyttelyyn.', NULL, FALSE, FALSE),
(2, 'A.10.5', 1, 'Päätöksen näyttelykiellosta ja tulosten poistamisesta tekee Kennelliiton hallitus. Päätöksentekoa Kennelliitossa ei estä se, että henkilö, jonka koiran käyttäytymisestä ilmoitus on tehty, ei ole käyttänyt hänelle annettua tilaisuutta vastineen antamiseen asiassa. Ensimmäisessä ja toisessa kappaleessa mainitut seuraamukset tulevat voimaan Kennelliiton hallituksen päätöksentekopäivänä.', NULL, FALSE, FALSE),
(2, 'A.11', 1, 'Koiran esittäjän asusteissa ei saa olla mainintaa kennelistä, kasvattajasta, omistajasta eikä esitettävästä koirasta.', NULL, FALSE, FALSE),
(2, 'A.11', 2, 'Koiran karvapeitteen kunnostaminen näyttelypaikalla on sallittu vain kampaamalla ja harjaamalla, ellei tarkoitukseen ole erikseen osoitettu erityistä trimmauspaikkaa. Koira saa olla kiinnitettynä trimmauspöydällä vain kunnostukseen tarvittavan ajan. Muutoinkin näytteilleasettajien on omalta osaltaan huolehdittava erityisen tarkoin näyttelypaikan siisteydestä.', NULL, FALSE, FALSE),
(2, 'A.12.1', 1, 'Näyttelyn järjestäjä ja ulkomuototuomari sopivat keskenään ennen näyttelyä ulkomuototuomarin arvosteltavaksi tulevien koirien lukumäärästä: suositeltava koiramäärä on 80 ja suurin mahdollinen 100. Ulkomuototuomarilla on oikeus kieltäytyä arvostelemasta suurempaa koiramäärää, kuin minkä hän on etukäteen näyttelyn järjestäjän kanssa sopinut. Jos ulkomuototuomarille ilmoitetaan enemmän koiria, kuin mitä hän on ilmoittanut etukäteen enintään arvostelevansa, siirretään ylimääräiset koirat muille ulkomuototuomareille ja siirrettävistä roduista on tuomarisihteerin neuvoteltava ulkomuototuomarin kanssa.', NULL, FALSE, FALSE),
(2, 'A.12.1', 2, 'Ulkomuototuomari voi kuitenkin suostua arvostelemaan kaikki hänelle ilmoitetut enintään 100 koiraa, mikäli hän katsoo selviytyvänsä siitä normaaliajassa ja arvostelun kärsimättä. Jos kyseessä on vaikeasti sovitettava ylitys, näyttelytoimikunta voi perustelluista syistä joustaa 100 koiraan saakka, lupa on neuvoteltava Kennelliiton kanssa. Yhden tai kahden rodun erikoisnäyttelyissä voidaan tuomarikohtainen enimmäiskoiramäärä ylittää. Asiasta on sovittava Kennelliiton kanssa.', NULL, FALSE, FALSE),
(2, 'A.12.1', 3, 'Jos ulkomuototuomarille on ilmoitettu vähemmän kuin 30 koiraa, näyttelytoimikunnalla on oikeus peruuttaa kutsu, kuitenkin niin, että tuomarille mahdollisesti aiheutuneet kulut korvataan.', NULL, FALSE, FALSE),
(2, 'A.12.2', 1, 'Rotua ei saa siirtää pois ulkomuototuomarilta, jotta sen tilalle voitaisiin siirtää jokin muu rotu. Muutoksesta on ilmoitettava näytteilleasettajille niin hyvissä ajoin, että heillä on mahdollisuus peruuttaa ilmoittautumisensa. Peruutusilmoituksen tulee olla postileimattu ennen näyttelyä.', NULL, FALSE, FALSE),
(2, 'A.12.2', 2, 'Jos tuomarimuutos joudutaan pakottavista syistä tekemään viikon sisällä ennen näyttelyä, näyttelytoimikunta ei ole velvollinen ilmoittamaan siitä näytteilleasettajille etukäteen. Näyttelytoimikunnan tulee kuitenkin mahdollisuuksien mukaan tiedottaa viime hetken tuomarimuutoksista. Tässä tapauksessa näytteilleasettajan tulee tehdä peruutusilmoitus kehään tai näyttelyn toimistoon ennen ko. rodun alkuperäistä arvioitua arvosteluaikaa.', NULL, FALSE, FALSE),
(2, 'A.12.2', 3, 'Jos rotu siirretään ulkomuototuomarille, joka on ilmoitettu ko. rodulle varalla olevaksi ulkomuototuomariksi Koiramme -lehdessä, ei ilmoittautumismaksua palauteta. Mikäli rodulle on ilmoitettu useampi kuin yksi varalla oleva tuomari, peruutustapauksissa ilmoittautumismaksu joudutaan palauttamaan.', NULL, FALSE, FALSE),
(2, 'A.12.3', 1, 'Kansallisissa näyttelyissä ryhmiä 1-10 arvostelevalla ulkomuototuomarilla on oltava arvosteluoikeudet vähintään puoleen ko. ryhmän Suomessa esiintyvistä roduista.', NULL, FALSE, FALSE),
(2, 'A.12.3', 2, 'Kansainvälisissä näyttelyissä ryhmiä 1-10 arvostelevalla ulkomuototuomarilla on oltava arvosteluoikeudet kaikkiin ko. ryhmän Suomessa esiintyviin rotuihin.', NULL, FALSE, FALSE),
(2, 'A.12.3', 3, 'Kansainvälisissä ja kaikkien rotujen näyttelyissä näyttelyn parhaan koiran valinnan saa tehdä kokenut tuomari, jolla on arvosteluoikeudet useille roduille useista FCI:n roturyhmistä ja lisäksi vähintään kahden kokonaisen roturyhmän arvosteluoikeudet.', NULL, FALSE, FALSE),
(2, 'A.12.3', 4, 'Muissa ryhmä- ja näyttelyn paras kilpailuissa voidaan ulkomuototuomariksi valita henkilö, jolla on arvosteluoikeudet useille roduille useista FCI:n ryhmistä.', NULL, FALSE, FALSE),
(2, 'A.12.3', 5, 'Yhdistetyissä ryhmissä esimerkiksi 4 ja 6 ja 7 ja 8 ryhmän parhaan voi arvostella ulkomuototuomari, jolla on arvostelu-oikeudet vähintään puoleen yhdistetyn ryhmän Suomessa rekisteröidyistä roduista.', NULL, FALSE, FALSE),
(2, 'A.12.3', 6, 'Englannin Kennel Clubin tuomarit: Englannin Kennel Clubin kokeneimmat ulkomuototuomarit voivat kansainvälisissä ja kaikkien rotujen näyttelyissä arvostella FCI:n ryhmiä 1-10, mikäli heillä on arvosteluoikeudet CC-tasolla suurimpaan osaan kyseisen ryhmän roduista.', NULL, FALSE, FALSE),
(2, 'A.12.4', 1, 'Ks. Voimassa oleva Suomen Kennelliiton yleinen jääviyssääntö.', NULL, FALSE, FALSE),
(2, 'A.13', 1, 'Kun koira on tuotu kehään mittausta tai laatuarvostelua varten, se on esitettävä kaikissa niissä luokissa ja kilpailuissa, joihin sen saamat palkinnot oikeuttavat sen osallistumaan.', NULL, FALSE, FALSE),
(2, 'A.13', 2, 'Koirien purennan ja kivesten tarkastamisen sekä mahdollisen mittauksen suorittaa arvosteleva ulkomuototuomari. Näyttelytoimikunnan edustaja voi erittäin painavista syistä antaa luvan jättää koira esittämättä (esimerkiksi ryhmäkilpailuissa). Kennelliiton hallitus voi poistaa ilman lupaa jatkokilpailuista pois jääneen koiran siinä näyttelyssä saavuttamat tulokset.', NULL, FALSE, FALSE),
(2, 'A.13', 3, 'Saksanpaimenkoirat voidaan arvostella ns. sovelletulla saksalaisella arvostelujärjestelmällä, mikäli arvosteleva ulkomuototuomari ja näyttelyn järjestäjä ovat siitä etukäteen keskenään sopineet. Tällöin laatumaininta osoitetaan vasta sitten, kun koko luokka on arvosteltu.', NULL, FALSE, FALSE),
(2, 'A.13', 4, 'Arvosteluluokat ovat koiranäyttelysääntöjen mukaiset.', NULL, FALSE, FALSE),
(2, 'A.13', 5, 'Kotimaisissa roduissa arvostelu annetaan myös suullisesti.', NULL, FALSE, FALSE),
(2, 'A.14', 1, 'Paras uros-/ paras narttuluokkaan ovat oikeutettuja osallistumaan virallisissa luokissa neljän parhaan joukkoon sijoittuneet SA:lla palkitut koirat.', NULL, FALSE, FALSE),
(2, 'A.14', 2, 'Rotujärjestöjen tai kennelyhdistysten samanaikaisesti samassa paikassa järjestämissä näyttelyissä voidaan ryhmäkilpailut yhdistää yhdeksi yhteiseksi loppukilpailuksi.', NULL, FALSE, FALSE),
(2, 'A.14', 3, 'Kansainvälisissä näyttelyissä ryhmäkilpailuihin voivat osallistua vain FCI:n hyväksymät rodut (ks. liite 2).', NULL, FALSE, FALSE),
(2, 'A.14', 4, 'Näyttelyissä voidaan järjestää myös epävirallinen kilpailu rotunsa parhaiden kotimaisten rotujen kesken, ”Paras Sinivalkoinen -koira”. Kilpailun arvostelee kotimainen tuomari, jolla on kyseisten rotujen arvosteluoikeudet.', NULL, FALSE, FALSE),
(2, 'A.15', 1, 'Näyttelytoimikunnan on jaettava ruusuke seuraavista saavutuksista ja palkintosijoista:', NULL, FALSE, FALSE),
(2, 'A.15', 2, 'Ruusukkeiden värien tulee vastata näyttelysääntöjen virallisia värejä.', NULL, FALSE, FALSE),
(2, 'A.15', 3, 'sertifikaatti: sinivalkoinen', NULL, TRUE, TRUE),
(2, 'A.15', 4, 'varasertifikaatti: vaaleansininen', NULL, TRUE, TRUE),
(2, 'A.15', 5, 'CACIB: valkoinen', NULL, TRUE, TRUE),
(2, 'A.15', 6, 'vara-CACIB: oranssi', NULL, TRUE, TRUE),
(2, 'A.15', 7, 'ROP: punakeltainen', NULL, TRUE, TRUE),
(2, 'A.15', 8, 'VSP: valkovihreä', NULL, TRUE, TRUE),
(2, 'A.15', 9, 'kunniapalkinto: liila', NULL, TRUE, TRUE),
(2, 'A.15', 10,'Suomen muotovalio: punavihreä', NULL, TRUE, TRUE),
(2, 'A.15', 11,'Näyttelytoimikunnan on jaettava esinepalkinto seuraavista saavutuksista ja palkintosijoista:', NULL, FALSE, FALSE),
(2, 'A.15', 12,'sertifikaatti (SERT)', NULL, TRUE, TRUE),
(2, 'A.15', 13,'CACIB', NULL, TRUE, TRUE),
(2, 'A.15', 14,'rotunsa paras (ROP)', NULL, TRUE, TRUE),
(2, 'A.15', 15,'vastakkaisen sukupuolen paras (VSP)', NULL, TRUE, TRUE),
(2, 'A.15', 16,'rotunsa paras ja VSP-pentu', NULL, TRUE, TRUE),
(2, 'A.15', 17,'rotunsa paras ja VSP-veteraani', NULL, TRUE, TRUE),
(2, 'A.15', 18,'rotunsa paras kasvattaja', NULL, TRUE, TRUE),
(2, 'A.15', 19,'ryhmäkilpailuissa sijoittuneet (Ryhmät 1-10, KASV 1-4, VET 1-4)', NULL, TRUE, TRUE),
(2, 'A.15', 20,'näyttelyn paras -kilpailussa sijoittuneet (BIS 1-4)', NULL, TRUE, TRUE),
(2, 'A.15', 21,'Näyttelytoimikunta voi halutessaan jakaa muistakin sijoituksista ja saavutuksista esinepalkintoja ja/tai ruusukkeita ja/tai nauhoja.', NULL, FALSE, FALSE),
(2, 'A.15', 22,'Näyttelysäännön mukainen palkintoruusuke tai ruokapalkinto ainoana vaihtoehtona ei ole tässä tarkoitettu esinepalkinto.', NULL, FALSE, FALSE),
(2, 'A.15', 23,'Sertifikaatista, varasertifikaatista, CACIBista ja vara-CACIBista annetaan näytteilleasettajalle arvostelleen ulkomuototuomarin allekirjoituksella vahvistettu edellä mainittua palkintoa osoittava Kennelliiton hyväksymä vahvistuskortti.', NULL, FALSE, FALSE),
(2, 'A.16', 1, 'Arvostelun aikana arvostelukehässä saavat olla arvosteltavien koirien ja niiden esittäjien lisäksi ainoastaan arvosteleva ulkomuototuomari, mahdolliset harjoitusarvostelijat, tarvittavat kehätoimitsijat sekä näyttelyn sujumisen edellyttämät näyttelytoimikunnan edustajat.', NULL, FALSE, FALSE),
(2, 'A.17', 1, 'Kennelliiton voimassaolevan muutoksenhakua koskevan ohjeen mukaan valitusmaksun maksamisvelvollisuus ei koske ao. näyttelyssä arvostelevaa tuomaria, toimikuntaa eikä toimikunnan edustajaa.', NULL, FALSE, FALSE)
;