DROP TABLE IF EXISTS `ruleSections`;

--
-- Table structure for table `ruleSections`
--

CREATE TABLE IF NOT EXISTS `ruleSections` (
  `ruleId` int(3) NOT NULL,
  `sectionId` varchar(10) NOT NULL,
  `parentSection` varchar(10) DEFAULT NULL,
  `sectionHeader` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`ruleId`, `sectionId`),
  FOREIGN KEY (ruleId) REFERENCES rules(ruleId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `ruleSections`
--

INSERT INTO `ruleSections` 
	(`ruleId`, `sectionId`, `parentSection`, `sectionHeader`) 
VALUES
	(1, '1', NULL, ' Yleistä'),
	(1, '2', NULL, ' Näyttelyn tarkoitus'),
	(1, '3', NULL, ' Osallistumisoikeus'),
	(1, '3.1', 3,  'Jääviys'),
	(1, '3.2', 3,  'Terveysmääräykset'),
	(1, '4', NULL, ' Ilmoittautuminen'),
	(1, '5', NULL, ' Ilmoittautumisen peruuttaminen '),
	(1, '6', NULL, ' Näytteilleasettajaa koskevia määräyksiä'),
	(1, '7', NULL, ' Vastuuvakuutus'),
	(1, '8', NULL, ' Ulkomuototuomarit'),
	(1, '9', NULL, ' Koirien arvostelu'),
	(1, '10', NULL, ' Arvosteluperusteet'),
	(1, '10.1', '10', ' Laatuarvostelu'),
	(1, '10.2', '10', ' Kilpailuarvoste'),
	(1, '11', NULL, ' Arvosteluluokat'),
	(1, '11.a', '11', 'Pikkupentuluokka (BABY)'),
	(1, '11.b', '11', 'Pentuluokka (PEK)'),
	(1, '11.c', '11', 'Junioriluokka (JUN)'),
	(1, '11.d', '11', 'Nuorten luokka (NUO)'),
	(1, '11.e', '11', 'Avoin luokka (AVO)'),
	(1, '11.f', '11', 'Käyttöluokka (KÄY)'),
	(1, '11.g', '11', 'Valioluokka (VAL)'),
	(1, '11.h', '11', 'Veteraaniluokka (VET)'),
	(1, '11.i', '11', 'Paras uros-/paras narttuluokka (PU/PN)'),
	(1, '11.j', '11', 'Rodun (ROP) ja vastakkaisen sukupuolen paras (VSP)'),
	(1, '11.k', '11', 'Kasvattajaluokka (KAS)'),
	(1, '11.l', '11', 'Best in Show kasvattajaluokka (BIS-KAS)'),
	(1, '11.m', '11', 'Jälkeläisluokka (JÄL)'),
	(1, '11.n', '11', 'Best in Show jälkeläisluokka (BIS-JÄL)'),
	(1, '11.o', '11', 'Best in Show veteraani -kilpailu (BIS-VET)'),
	(1, '11.p', '11', 'Ryhmän paras -kilpailu (RYP)'),
	(1, '11.q', '11', 'Best in Show (BIS)'),
	(1, '12', NULL, ' Palkintoa osoittavat värit'),
	(1, '13', NULL, ' Arvostelun muuttaminen'),
	(1, '14', NULL, ' Muut ohjeet'),
	(1, '15', NULL, ' Valitukset'),
	(1, '16', NULL, ' Voimassaolo'),

	(2, 'A', NULL, 'Näyttelysääntöjä täydentävät ohjeet'),
	(2, 'A.1', 'A', 'Yleistä'),
	(2, 'A.2', 'A', 'Osallistumisoikeus'),
	(2, 'A.3', 'A', 'Ilmoittautuminen'),
	(2, 'A.3.1', 'A.3', 'Yleistä'),
	(2, 'A.3.2', 'A.3', 'Luokat ja niiden vaihtaminen'),
	(2, 'A.3.3', 'A.3', 'Maksut ja maksupalautukset'),
	(2, 'A.3.4', 'A.3', 'Ilmoittautumisen peruuttaminen'),
	(2, 'A.4', 'A', 'Sertifikaatti'),
	(2, 'A.5', 'A', 'Kansainvälinen sertifikaatti l. CACIB'),
	(2, 'A.6', 'A', 'Siirto rodusta tai rotumuunnoksesta toiseen'),
	(2, 'A.7', 'A', 'Kivesvikaisuus ja sen toteaminen'),
	(2, 'A.8', 'A', 'Sekarotuisuus ja sen toteaminen'),
	(2, 'A.9', 'A', 'Viaksi katsottavan tai muun ominaisuuden korjaaminen tai muuttaminen'),
	(2, 'A.10', 'A', 'Koiran käyttäytymisestä näyttelyssä tehtävät ilmoitukset, niiden käsittely ja seuraukset'),
	(2, 'A.10.1', 'A.10', 'Toiminta ja seuraukset laatuarvostelussa'),
	(2, 'A.10.2', 'A.10', 'Toiminta ja seuraukset laatuarvostelun ulkopuolella'),
	(2, 'A.10.3', 'A.10', 'Ilmoitukset'),
	(2, 'A.10.4', 'A.10', 'Ilmoitusmenettely'),
	(2, 'A.10.5', 'A.10', 'Päätöksenteko'),
	(2, 'A.11', 'A', 'Näytteilleasettajaa koskevia määräyksiä'),
	(2, 'A.12', 'A', 'Ulkomuototuomarit'),
	(2, 'A.12.1', 'A.12', 'Ulkomuototuomarikohtainen koiramäärä'),
	(2, 'A.12.2', 'A.12', 'Ulkomuototuomarimuutokset'),
	(2, 'A.12.3', 'A.12', 'Ulkomuototuomarin oikeudet arvostella ryhmäkilpailuja'),
	(2, 'A.12.4', 'A.12', 'Ulkomuototuomarin esteellisyys'),
	(2, 'A.13', 'A', 'Koirien arvostelu'),
	(2, 'A.14', 'A', 'Arvosteluluokat'),
	(2, 'A.15', 'A', 'Palkinnot'),
	(2, 'A.16', 'A', 'Muut ohjeet'),
	(2, 'A.17', 'A', 'Valitukset'),
	(2, 'B', NULL, 'Näyttelyiden järjestämisohje'),
	(2, 'B.1', 'B', 'Järjestämisoikeus'),
	(2, 'B.1.1', 'B.1', 'Suomen Kennelliitto'),
	(2, 'B.1.2', 'B.1', 'Kennelpiirit'),
	(2, 'B.1.3', 'B.1', 'Kennelpiirien jäsenyhdistykset'),
	(2, 'B.1.4', 'B.1', 'Rotujärjestöt ja rotua harrastavat yhdistykset'),
	(2, 'B.1.5', 'B.1', 'Poikkeaminen kennelpiirien rajoista'),
	(2, 'B.2', 'B', 'Näyttelylajit'),
	(2, 'B.2.1', 'B.2', 'Kansainväliset näyttelyt'),
	(2, 'B.2.2', 'B.2', 'Pohjoismaiset näyttelyt'),
	(2, 'B.2.3', 'B.2', 'Kaikkien rotujen näyttelyt'),
	(2, 'B.2.4', 'B.2', 'Ryhmänäyttelyt'),
	(2, 'B.2.4.1', 'B.2.4', 'Vaihtoehto 1'),
	(2, 'B.2.4.2', 'B.2.4', 'Vaihtoehto 2'),
	(2, 'B.2.4.3', 'B.2.4', 'Vaihtoehto 3'),
	(2, 'B.2.4.4', 'B.2.4', 'Vaihtoehto 4'),
	(2, 'B.2.4.5', 'B.2.4', 'Vaihtoehto 5'),
	(2, 'B.2.5', 'B.2', 'Erikoisnäyttelyt'),
	(2, 'B.2.6', 'B.2', 'Tukinäyttelyt'),
	(2, 'B.3', 'B', 'Näyttelyiden hakumenettely'),
	(2, 'B.3.1', 'B.3', 'Yleistä'),
	(2, 'B.3.2', 'B.3', 'Kansainväliset ja kaikkien rotujen näyttelyt'),
	(2, 'B.3.3', 'B.3', 'Ryhmänäyttelyt'),
	(2, 'B.3.4', 'B.3', 'Erikoisnäyttelyt'),
	(2, 'B.3.5', 'B.3', 'Tukinäyttelyt'),
	(2, 'B.4', 'B', 'Näyttelyiden ajallinen sovittaminen'),
	(2, 'B.5', 'B', 'Tulosten toimittaminen'),
	(2, 'B.6', 'B', 'Näyttelymaksuosuus'),
	(2, 'B.7', 'B', 'Näyttelytoimikunta'),
	(2, 'B.7.1', 'B.7', 'Toimikunnan kokoonpano'),
	(2, 'B.7.2', 'B.7', 'Näyttelyn sihteeri'),
	(2, 'B.7.3', 'B.7', 'Näyttelyohjaaja'),
	(2, 'B.8', 'B', 'Näyttelypaikka'),
	(2, 'B.9', 'B', 'Näyttelystä tiedottaminen'),
	(2, 'B.9.1', 'B.9', 'Ilmoitus Koiramme -lehdessä'),
	(2, 'B.9.2', 'B.9', 'Tiedote'),
	(2, 'B.10', 'B', 'Ilmoittautumisten käsittely ja näyttelyluettelo'),
	(2, 'B.10.1', 'B.10', 'Ilmoittautumisten vastaanotto'),
	(2, 'B.10.2', 'B.10', 'Aikataulun laadinta'),
	(2, 'B.10.3', 'B.10', 'Kirjeet näytteilleasettajille'),
	(2, 'B.10.4', 'B.10', 'Näyttelyluettelo'),
	(2, 'B.11', 'B', 'Ulkomuototuomarit'),
	(2, 'B.11.1', 'B.11', 'Ulkomuototuomarilistan laadinta'),
	(2, 'B.11.2', 'B.11', 'Yhteydenpito ulkomuototuomareihin'),
	(2, 'B.11.3', 'B.11', 'Ulkomaisten ulkomuototuomareiden ohjaus'),
	(2, 'B.11.4', 'B.11', 'Harjoitusarvostelijat'),
	(2, 'B.12', 'B', 'Kehätoimitsijat'),
	(2, 'B.13', 'B', 'Eläinlääkäri'),
	(2, 'B.14', 'B', 'Kulukorvaukset ja niiden maksaminen'),
	(2, 'B.14.1', 'B.14', 'Matkakorvaus'),
	(2, 'B.14.2', 'B.14', 'Majoitus'),
	(2, 'B.14.3', 'B.14', 'Päiväraha'),
	(2, 'B.14.4', 'B.14', 'Muut määräykset'),
	(2, 'B.14.5', 'B.14', 'Muuta huomioitavaa'),
	(2, 'B.15', 'B', 'Kennelliiton neuvontapiste'),
	(2, 'B.16', 'B', 'Poikkeukset'),

	(3, '1', NULL, 'Kaikkia rotuja koskevat vaatimukset'),
	(3, '1.1', '1', 'Muotovalion arvo (FI MVA)'),
	(3, '1.2', '1', 'Agilityvalion arvo (FI AVA)'),
	(3, '1.3', '1', 'Hyppyvalion arvo (FI AVA-H)'),
	(3, '1.4', '1', 'Jäljestämisvalion arvo (FI JVA)'),
	(3, '1.5', '1', 'Koiratanssivalionarvo (FI KTV ja FI KTV-V)'),
	(3, '1.5.1', '1.5', 'Seuraaminen musiikin tahdissa (Heelwork to Music FI KTV)'),
	(3, '1.5.2', '1.5', 'Vapaaohjelma (Freestyle FI KTV-V)'),
	(3, '1.6', '1', 'Käyttövalion arvo (FI KVA)'),
	(3, '1.6.1', '1.6', 'Palveluskoirakokeiden käyttövalion arvo'),
	(3, '1.7', '1', 'Käyttövalion arvo (FI KVA-J)'),
	(3, '1.8', '1', 'Metsästysvalion arvo (FI KVA-L ja FI KVA-M)'),
	(3, '1.9', '1', 'Paimennusvalion arvo (FI PVA)'),
	(3, '1.10', '1', 'Rally-tokovalion arvo (FI RTVA)'),
	(3, '1.11', '1', 'Tottelevaisuusvalion arvo (FI TVA)'),
	(3, '1.12', '1', 'Vesipelastusvalion arvo (FI VPVA)'),
	(3, '1.13', '1', 'Vetovalion arvo (FI VVA)'),
	(3, '1.14', '1', 'Pohjoismaiden käyttövalion arvo (POHJ KVA)'),
	(3, '1.15', '1', 'Pohjoismaiden muotovalion arvo (POHJ MVA)'),
	(3, '1.16', '1', 'Erinäiset säännökset'),
	(3, '1.17', '1', 'Lyhenteiden selitykset'),

	(4, 'A', NULL, 'Yleinen valitusmenettely'),
	(4, 'A.1', 'A', 'Kokeet, kilpailut ja luonnetestit'),
	(4, 'A.1.1', 'A.1', 'Valitusaika, valitusmaksu ja jatkovalitukset '),
	(4, 'A.2', 'A', 'Näyttelyt'),
	(4, 'A.2.1', 'A.2', 'Valitusaika ja valitusmaksu'),
	(4, 'A.2.2', 'A.2', 'Jatkovalitukset'),
	(4, 'B', NULL, 'Oikaisuvaatimusmenettely'),

	(5, '1', NULL, 'Määritelmiä'),
	(5, '2', NULL, 'Salassapito'),
	(5, '3', NULL, 'Koiran suorituskykyyn vaikuttaminen'),
	(5, '4', NULL, 'Dopingnäytteiden ottamisen perusteet'),
	(5, '4.1', '4', 'Lakiperusteinen dopingvalvonta'),
	(5, '4.2', '4', 'Sattumanvarainen sekä koiran menestykseen perustuva dopingvalvonta'),
	(5, '4.3', '4', 'Poikkeavaan suoritukseen tai muuhun perusteltuun epäilyyn perustuva dopingvalvonta'),
	(5, '5', NULL, 'Dopingnäytteiden ottamista koskeva menettely'),
	(5, '6', NULL, 'Rangaistukset'),
	(5, '7', NULL, 'Näytteenoton ja tutkimuksen kustannukset'),
	(5, '8', NULL, 'Täydentävät ohjeet'),

	(7, '1', NULL, 'Näytteenottopaikka'),
	(7, '2', NULL, 'Näytteenotto'),
	(7, '2.1', '2', 'Dopingvalvojan tehtävät'),
	(7, '2.2', '2', 'Näytteenottovälineet'),
	(7, '2.3', '2', 'Virtsa- ja verinäytteet'),
	(7, '2.4', '2', 'Karva- ja kirsunäytteet'),
	(7, '2.5', '2', 'Lomakkeen täyttö'),
	(7, '2.6', '2', 'Virtsanäytteenoton viimeistely'),
	(7, '3', NULL, 'Näytteiden käsittely ja jatkotoimenpiteet'),
	(7, '4', NULL, 'Dopingsääntöä täydentävät Kennelliiton hallituksen erikseen antamat ohjeet koirien lääkinnästä ja hoidosta'),
	(7, '5', NULL, 'Poikkeuslupamenettely tiettyä lääkitystä pysyvän sairauden hoitoon saavan koiran osallistumiseksi koiratapahtumiin'),

	(6, '1', NULL, '§'),
	(6, '2', NULL, '§'),
	(6, '3', NULL, '§'),
	(6, '4', NULL, '§'),

	(8, '0', NULL, 'Sisällys'),
	(8, '1', NULL, 'Yleistä'),
	(8, '2', NULL, 'Anomukset'),
	(8, '3', NULL, 'Luokat'),
	(8, '4', NULL, 'Pohjoismainen sertifikaatti'),
	(8, '5', NULL, 'Tuomarit'),
	(8, '6', NULL, 'Pohjoismaiden muotovalio'),
	(8, '7', NULL, 'Siirtymäkauden ohjeet 2018-2019'),

	(9, '1', NULL, 'Johdanto'),
	(9, '2', NULL, 'Soveltaminen'),
	(9, '2.1', '2', 'Rotukohtaisesti tarkkailtavat piirteet ja laatuarvostelu'),
	(9, '2.2', '2', 'Kirjalliset arvostelut'),
	(9, '2.3', '2', 'Tuomariraportit'),
	(9, '2.4', '2', 'Liioiteltu esittäminen'),
	(9, '3', NULL, 'Kaikkia rotuja koskevat ohjeet'),
	(9, '3.1', '3', 'Hengitys'),
	(9, '3.2', '3', 'Silmät'),
	(9, '3.3', '3', 'Purenta ja hampaat'),
	(9, '3.4', '3', 'Paino'),
	(9, '3.5', '3', 'Iho ja turkki'),
	(9, '3.6', '3', 'Liikkeet'),
	(9, '3.7', '3', 'Käyttäytyminen'),
	(9, '4', NULL, 'Rotutyypit'),
	(9, '4.1', '4', 'Brakykefaliset (lyhytkalloiset) rodut'),
	(9, '4.2', '4', 'Kääpiörodut'),
	(9, '4.3', '4', 'Kondrodystrofiset rodut'),
	(9, '4.4', '4', 'Molossirodut'),
	(9, '5', NULL, 'FCI RYHMÄ 1 Lammas- ja karjakoirat (paitsi sveitsinpaimenkoirat)'),
	(9, '5.1', '5', 'Pitkäkarvainen ja sileäkarvainen skotlanninpaimenkoira (collie)'),
	(9, '5.2', '5', 'Saksanpaimenkoira'),
	(9, '6', NULL, 'FCI RYHMÄ 2 Pinserit, snautserit, molossityyppiset ja sveitsinpaimenkoirat'),
	(9, '6.1', '6', 'Bullmastiffi - brakykefalinen, molossityyppinen'),
	(9, '6.2', '6', 'Englanninbulldoggi - brakykefalinen'),
	(9, '6.3', '6', 'Bordeauxindoggi - brakykefalinen, molossityyppinen'),
	(9, '6.4', '6', 'Bokseri - brakykefalinen, molossityyppinen'),
	(9, '6.5', '6', 'Tanskandoggi - molossityyppinen'),
	(9, '6.6', '6', 'Mastiffi - molossityyppinen'),
	(9, '6.7', '6', 'Napolinmastiffi - molossityyppinen'),
	(9, '6.8', '6', 'Bernhardinkoira, pitkäkarvainen ja lyhytkarvainen - molossityyppinen'),
	(9, '6.9', '6', 'Shar pei'),
	(9, '7', NULL, 'FCI RYHMÄ 3 Terrierit'),
	(9, '7.1', '7', 'Bullterrieri / kääpiöbullterrieri'),
	(9, '7.2', '7', 'Norwichinterrieri'),
	(9, '7.3', '7', 'Staffordshirenbullterrieri'),
	(9, '7.4', '7', 'Valkoinen länsiylämaanterrieri'),
	(9, '7.5', '7', 'Yorkshirenterrieri - kääpiöterrieri'),
	(9, '8', NULL, 'FCI RYHMÄ 4 Mäyräkoirat'),
	(9, '8.1', '8', 'Mäyräkoirat - kondrodystrofinen tyyppi'),
	(9, '9', NULL, 'FCI RYHMÄ 5 Pystykorvat ja alkukantaiset koirat'),
	(9, '9.1', '9', 'Chow chow'),
	(9, '9.2', '9', 'Saksanpystykorva, pomeranian - kääpiöpystykorva'),
	(9, '10', NULL, 'FCI RYHMÄ 6 Ajavat ja jäljestävät koira'),
	(9, '10.1','10','Basset hound - kondrodystrofinen tyyppi'),
	(9, '10.2','10','Vihikoira'),
	(9, '11', NULL, 'FCI RYHMÄ 7 Kanakoirat'),
	(9, '11.1','11','Bracco italiano'),
	(9, '11.2','11','Spinone'),
	(9, '12', NULL, 'FCI RYHMÄ 8 Noutajat, ylösajavat koirat ja vesikoirat'),
	(9, '12.1','12','Amerikancockerspanieli'),
	(9, '12.2','12','Clumberinspanieli'),
	(9, '12.3','12','Sileäkarvainen noutaja'),
	(9, '13', NULL, 'FCI RYHMÄ 9 Seurakoirat ja kääpiökoirat'),
	(9, '13.1','13','Griffon belge/bruxellois & petit brabancon - brakykefalinen tyyppi'),
	(9, '13.2','13','Bostoninterrieri - brakykefalinen, pieni molossityyppinen'),
	(9, '13.3','13','Cavalier kingcharlesinspanieli'),
	(9, '13.4','13','Chihuahua, lyhytkarvainen & pitkäkarvainen'),
	(9, '13.5','13','Kiinanharjakoira, karvaton muunnos'),
	(9, '13.6','13','Ranskanbulldoggi - brakykefalinen, pieni molossityyppinen'),
	(9, '13.7','13','Japanese chin - brakykefalinen tyyppi'),
	(9, '13.8','13','Kingcharlesinspanieli - brakykefalinen tyyppi'),
	(9, '13.9','13','Kiinanpalatsikoira/pekingeesi - brakykefalinen ja kondrodystrofinen tyyppi'),
	(9, '13.10','13','Mopsi - brakykefalinen, pieni molossityyppinen'),
	(9, '13.11','13','Shih tzu - brakykefalinen, kondrodystrofinen'),
	(9, '14', NULL, 'FCI RYHMÄ 10 Vinttikoirat'),
	(9, '14.1','14','Irlanninsusikoira'),
	(9, '14.2','14','Venäjänvinttikoira'),
	(9, '15', NULL, 'LIITE 1 RKO:n taustaa'),
	(9, '16', NULL, 'LIITE 2 Hengitysvaikeuksien arviointi näyttelykehässä'),
	(9, '17', NULL, 'LIITE 3 Silmäongelmat'),
	(9, '17.1','17','Silmäongelmia mahdollisesti aiheuttavat anatomiset piirteet'),
	(9, '17.2','17','Silmäsairauksien oireet'),
	(9, '17.3','17','Brakykefalisten rotujen erityispiirteitä'),
	(9, '17.4','17','Rodut joilla on runsaasti löysää nahkaa'),
	(9, '17.5','17','Silmäongelmien arviointi laatuarvostelussa'),
	(9, '17.6','17','Kilpailuarvostelussa huomioon otettavaa')
;
